### ISSUE TITLE
PDF renderer uses US date format (month/day/year)

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-time#1010]

**Comment by fniessink** [comment]
Tried changing the locale of the renderer container via by setting LC_CTYPE to en_GB.UTF-8, but apparently locale is not installed in the container because it complained: `ERROR:browser_main_loop.cc(279)] Gtk: Locale not supported by C library. Using the fallback 'C' locale.`

**Comment by fniessink** [comment]
Maybe we can create our own version of the renderer with locales included.

**Comment by eric-nieuwland** [comment]
Might want to switch to a complete other method of producing PDFs, like reportlab (https://pypi.org/project/reportlab/)

**Comment by fniessink** [comment]
Using reportlab would amount to creating a second UI. The result would probably be better than exporting HTML to PDF, but I'm not sure it's worth the effort.
