### ISSUE TITLE
Comments not visible or partially visible

### ISSUE THREAD

**Issue by denniebouman** [ICTU/quality-time#10183]
**Describe the bug**
Comments not visible or partially visible

**To Reproduce 1-2**
Steps to reproduce the behaviour:
1. Add comment with a URL with many characters (250+)
2. Comment section is empty

**To Reproduce 2-2**
Steps to reproduce the behaviour:
1. Add comment with multiple short URL's 
2. Comment section only shows a few URL's

**Expected behaviour**
See comment and URL

**Your environment (please complete the following information):**
 - Browser: Chrome
 - Quality-time version: v5.17.1

**Comment by fniessink** [comment]
This is caused by the code that trims long comments not taking HTML into account.
