### ISSUE TITLE
Option to add subreports to reports

### ISSUE THREAD

**Issue by enwelder** [ICTU/quality-time#1040]
In case of a System / application that consists of many subsystems, it might be beneficial to have sub reports of reports.

We have an application with many subjects (> 50) leading to more than 1000 metrics on one page. The page becomes a bit slow and is not very easy to grasp. However, we would like to combine several of the subjects to a report of a combined subsystem, ie a child report of the main report.

**Now:**
``` 
report
   subject 1
   subject 2
   ...
   subject n
```

**Requested:**
```
report
   subject 1
   subject 2
   ...
   subject n
   subreport 1
       subject 1
       subject 2
       ...
       subject n
   subreport 2
       subject 1
       subject 2
       ...
       subject n
   subreport n
       subject 1
       subject 2
       ...
       subject n
```

**Comment by fniessink** [comment]
One work-around to achieve something like this right now is to have multiple reports, give all metrics in all those reports the same tag (e.g. "combined"), and then use the "combined" tag report as combined report. The obvious disadvantage is that all metrics would have to have the "combined" tag.

**Comment by fniessink** [comment]
A thing to remember when designing this is that having separate subreports makes it harder to export the report to pdf.
