### ISSUE TITLE
Measuring red metrics will count itself when target is not met

### ISSUE THREAD

**Issue by Erik-Stel** [ICTU/quality-time#1165]
For our project we like to have a report that shows the overall red metrics. By using Quality Time as a source this is possible. A funny situation occurs: as soon as we cross our target, the metric itself will become red and be counted. So we either have 4 or 6 red issues, because as we reach target 5, the metric itself will become red and be counted. Would it be possible to prevent 'self counting'? If it is too difficult to remove 'self' that is okay too. No high priority.

**Comment by fniessink** [comment]
This is possible right now by making sure the "Metrics" metric itself isn't in the set of metrics that it counts. You can limit the metrics it counts by:

- report (name or identifier): the "Metrics" metric would have to be in a different report than the one(s) it's selected to measure,
- source type: you would have to select all source types except Quality-time,
- metric status: that won't help here,
- metric type: you would have to select all metric types except "Metrics",
- tag: you would have to give all metrics a tag except the "Metrics" metrics.

It seems the first option is the most convenient work-around if you don't mind the extra report with "Metrics" metrics.

Excluding "self" might be an option based on the unique metric id that each metric has.

**Comment by fniessink** [comment]
On second thought, I've decided not to fix this because the Metrics metric is counting the number of (red) metrics correctly.
