### ISSUE TITLE
Feature request: open source links in new window/tab

### ISSUE THREAD

**Issue by Erik-Stel** [ICTU/quality-time#1203]
Opening source links in the same window will, when returning to QT using the back-button, result in coming back to the main QT screen. This means losing the focus of your work.

I added a PR #1202 for this issue.

**Comment by fniessink** [comment]
WCAG recommends to be conservative with links opening in new windows (see https://www.w3.org/TR/WCAG20-TECHS/G200.html). There are two exceptions, one of which reads: "Opening a page containing context-sensitive information, such as help instructions, or an alternate means of completing a form, such as a calendar-based date picker, will significantly disrupt a multi-step workflow, such as filling in and submitting a form, if the page is opened in the same window or tab." I guess you could (and would) argue that a source link provides context-sensitive information, as in detail information of a metric that you're looking at. Okay, let's do this.
