### ISSUE TITLE
Feature request: Make 'Trend' or '<Source Link>' the default tab on a Measurement row

### ISSUE THREAD

**Issue by Erik-Stel** [ICTU/quality-time#1206]
By default the 'Metric' tab is shown/has focus when a Measurement row is opened. On the 'Metric' tab (as well as the 'Sources' tab) there are only settings. For normal/regular usage, these are not very interesting to a user and settings don't need to be changed often. The trendline (graph) or source link (rows of issues for example) are much more informative. The later tab is not always available, but could be considered the most informative because it shows the relevant issues instead of the aggregated measurement of a trend value. If a source link tab is missing, the trendline tab seems most informative. Could this become the default behaviour? Ie give source link tab focus and if not available give the trend tab focus.

See screenshot below in which the source link (SonarQube in this case) tab is opened:
![image](https://user-images.githubusercontent.com/6714870/83758506-7bb28100-a672-11ea-8717-fc8b8612dacd.png)

**Comment by fniessink** [comment]
I agree that from a user perspective, making the trend or details tab the default would be best. Problem however is that the information for the metric and sources tabs is already present in the browser when the user expands a metric, but the information for the trend and details (warnings/violations/etc) tabs is retrieved using separate API calls, at the moment the user expands the metric. The trend and details tabs are only drawn after the data arrives, so having them on the left would make the interface jitterish. I'm pretty sure preloading the trend and detail data for all metrics will be too expensive. If you have ideas on how to solve this though, I'm all ears.

**Comment by Erik-Stel** [comment]
I understand. I am not a big fan of changing the focus once the tab content is created. (Have you ever witnessed the horrible SharePoint/O365 interface in which lists or menus change right under your cursor, making you click the wrong item?!) Do you know in advance whether such a tab should be present? Cause in that case, you could already make that tab and give it focus. The content would arrive just a little later (showing a spinner in place of the content while waiting).

**Comment by fniessink** [comment]
Yes, that's a good idea. The frontend code knows whether or not there is historical data (because of the recent data needed for the spark line graphs) so could use that to decide to create a trend tab.

**Comment by Sebastiaan127001** [comment]
%VOTE

**Comment by fniessink** [comment]
Will be implemented via #4172.
