### ISSUE TITLE
Notify teams through MS Teams Webhook of changes

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-time#1223]
Metric status changes: just "becomes red", or also "becomes yellow", "becomes green", "becomes grey", "becomes white"? Configurable?

Limit notifications to certain reports, subjects, metrics, source (types), tags?

Bundle changes?

Include URL to the relevant report in the notification

**Comment by ds-o** [comment]
@fniessink is this going to be built in such a way that Jira could also be added as a destination? But not as an automatic notifier. This would allow a dev team to create a Jira ticket directly from a security issue in QT. I would like to implement this:

- A button "Send to Jira" in a metric source detail-row.
- After pressing the button, an API call to Notifier is made "POST /notify/jira/" with in the body the issue Title, Description, Jira Project.
- Notifier connects to the Jira API that is configured in the ENV variables and creates a new ticket in Jira.

Another option would be to built this logic inside the frontend & server. Do you have a preference?

**Comment by fniessink** [comment]
We have an issue open for this: #1389. I wouldn't want to combine it with the notification feature. I'd prefer to have this implemented in the server and the frontend. Each Quality-time instance or report could have a Jira configured that the "Open issue" button (i.e. the frontend) would use to open an issue. I think having the frontend open the issue could have the advantage that the user may already be logged in and in that case doesn't need to provide credentials to Jira.
