### ISSUE TITLE
Add button for "scroll to top" or 'home"

### ISSUE THREAD

**Issue by raginggoblin** [ICTU/quality-time#1231]
At RWS we have a large set of projects. We display these side by side as reports. When you click on one of the pie charts you scroll down to the details of that project. The back button however takes you back to the root. It would be very convenient when there is a back button functionality. 

Several possible approaches come to mind:
1) Change standard back button functionality so that it takes you to the top of the page.
2) Add a link/button next to the title of the project with 'home' that scrolls to the top.
3) On several mobile messaging apps a floating down arrow is shown when you scroll up in your history. You could add a floating arrow up button as soon as you scroll down.

**Comment by fniessink** [comment]
I like suggestion nr 3. Should be possible with the [Semantic UI React Sticky module](https://react.semantic-ui.com/modules/sticky/).

**Comment by raginggoblin** [comment]
Would be very nice, tx, here is a screenshot of my Signal Desktop App. In the lower right corner you can view the arrow button.
![Screenshot from 2020-06-17 10-35-46](https://user-images.githubusercontent.com/1873470/84876178-3e44ef00-b087-11ea-87ff-3234e4c2f672.png)

**Comment by fniessink** [comment]
I opted for option 2 in the end because a floating button on the left or right hand side of the screen would sometimes overlap with the other buttons. Especially the overlap with the delete buttons on the right hand side of the screen would be dangerous.

**Comment by raginggoblin** [comment]
Tx
