### ISSUE TITLE
Scrolling issues with v 2.4.0

### ISSUE THREAD

**Issue by enwelder** [ICTU/quality-time#1260]
Since the latest release 2.4.0 we notice that the scrolling is behaving differently. When scrolling the report, the screen turns white as long as it is being scrolled. After stopping the scrolling, it takes some time for the screen to render again. 

We do have a rather large report with about 60 subjects and each about 20 metrics.

![image](https://user-images.githubusercontent.com/14042813/85529699-9fcc0700-b60d-11ea-8bc6-99d89daca23a.png)

**Comment by fniessink** [comment]
Hmm, there's a new event handler listening to scroll events to enable the "scroll to dashboard" button in the menu bar as soon as the dashboard isn't completely visible anymore. The event handler is probably too slow or blocking the rendering.
