### ISSUE TITLE
Add the option to connect to Gitlab with basic authentication (user/pass)

### ISSUE THREAD

**Issue by denniebouman** [ICTU/quality-time#1293]
Like we already have for Jenkins. For Gitlab now we only have a "private token".

**Comment by fniessink** [comment]
I'm curious, why would you want to use basic authentication? A private token can be limited in scope and can be revoked at any time.

**Comment by denniebouman** [comment]
private response by email

**Comment by fniessink** [comment]
@denniebouman Is this still relevant?

**Comment by denniebouman** [comment]
@fniessink not necessarily, private token works fine too

**Comment by fniessink** [comment]
Thanks. Closing this issue then.
