### ISSUE TITLE
Changing the order of tabs for metrics

### ISSUE THREAD

**Issue by ds-o** [ICTU/quality-time#1300]
It would be nice if the tab with metric-details would be shown as the first tab. For example in the OWASP Dependency Check Metric, at the moment you have to expand and then navigate to the 4th tab.

![image](https://user-images.githubusercontent.com/21058511/87402972-91458f80-c5bc-11ea-8cb3-59dd561cf864.png)

**Comment by fniessink** [comment]
Duplicate of #1206.
