### ISSUE TITLE
Allow an HTTPS metric source to have a self signed certificate

### ISSUE THREAD

**Issue by ds-o** [ICTU/quality-time#1375]
When providing an HTTPS URL as a Metric Source, the collector cannot fetch the report if the HTTPS connection is using a self-signed certificate, it displays the following error:

ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)')]

**Comment by fniessink** [comment]
@dicksnel Can you send me an example URL? Privately of course.

**Comment by ds-o** [comment]
@fniessink I was using a local setup with dependency-check. The URL was https://localhost/test/dependencycheck.xml. 

I can make a PR to disable certificate checks for remote reports?

**Comment by fniessink** [comment]
I'd appreciate a PR. According to https://docs.aiohttp.org/en/stable/client_reference.html#tcpconnector, it should as simple as passing `ssl=False` to the TCPConnector of the ClientSession that is used to collect the metrics:

```diff
diff --git a/components/collector/src/base_collectors/metrics_collector.py b/components/collector/src/base_collectors/metrics_collector.py
index 8c8b66b0..a37715f7 100644
--- a/components/collector/src/base_collectors/metrics_collector.py
+++ b/components/collector/src/base_collectors/metrics_collector.py
@@ -70,8 +70,8 @@ class MetricsCollector:
             self.record_health()
             logging.info("Collecting...")
             async with aiohttp.ClientSession(
-                    connector=aiohttp.TCPConnector(limit_per_host=20), raise_for_status=True, timeout=timeout,
-                    trust_env=True) as session:
+                    connector=aiohttp.TCPConnector(limit_per_host=20, ssl=False), raise_for_status=True,
+                    timeout=timeout, trust_env=True) as session:
                 with timer() as collection_timer:
                     await self.collect_metrics(session, measurement_frequency)
             sleep_duration = max(0, max_sleep_duration - collection_timer.duration)
```
