### ISSUE TITLE
Create Jira Issue from finding

### ISSUE THREAD

**Issue by bs0man** [ICTU/quality-time#1389]
It would be nice to have a 'Create Jira issue' link or button next to the each finding which will create a Jira issue in a new tab using prefilled entity/vulnerability data.

https://confluence.atlassian.com/jirakb/how-to-create-issues-using-direct-html-links-in-jira-server-159474.html.

There must also be an option for the admin to set the Jira project ID, and Issue Type per report.

**Comment by fniessink** [comment]
We also need a way to refer back to the metric that the Jira issue is about. Issue #1266 would help with that.

Question: would you want to create Jira issues about metrics, or about the metric details (e.g. a single failed Jenkins job or a single SonarQube violation), or both?

**Comment by bdtesty** [comment]
Both but first priority would be details. For example when there's a finding / security violation from OWASP or Snyk we can easily create Jira tickets from the dashboard.

**Comment by fniessink** [comment]
This has been possible for a while now.
