### ISSUE TITLE
Add Gitleaks Collector

### ISSUE THREAD

**Issue by bdtesty** [ICTU/quality-time#1398]
Gitleaks is a open-source SAST tool for detecting hardcoded secrets like passwords, api keys, and tokens in git repos. Gitleaks aims to be the easy-to-use, all-in-one solution for finding secrets, past or present, in your code.

https://github.com/zricethezav/gitleaks

Gitleaks report is in JSON format. We can use the Defect Dojo parser as inspiration:

https://github.com/DefectDojo/django-DefectDojo/blob/e0fa585ee770bd0b15ba4a73bd81e6cc043650fd/dojo/tools/gitleaks/parser.py

Note that all secrets will need to be masked / redacted before stored into quality time.

**Comment by fniessink** [comment]
We don't currently use Gitleaks at ICTU (@dicksnel, should we though?) so a PR would be appreciated.

**Comment by ds-o** [comment]
@fniessink I think it may be useful to check if no dev-secrets like access keys or Azure keys are stored in the source codes that ICTU delivers.
