### ISSUE TITLE
Code to remove on the next major version of Quality-time

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-time#1416]
Issues and changes:

- [x] #1415:
    - [x] Remove the 'Ready user story point' metric from the Quality-time metric types in the data model
    - [x] Remove the 'Ready user story point' metric from the unit test `DataModelSpecificSourcesTest.test_quality_time_metric_type_parameter()`
    - [x] Migration code in the database initialization module
- [x] #1492:
    - [x] Old key generation in OWASP ZAP collector
- [x] #2155 
   - [x]  Dropping of the "start_1" index in the database initialization module

**Comment by emdv88** [comment]
- [x] Remove server endpoint /api/v3/reports
- [x] Remove server endpoint /api/v3/tagreport/<tag>
