### ISSUE TITLE
Generic Security Warnings

### ISSUE THREAD

**Issue by bdtesty** [ICTU/quality-time#1479]
It would be nice to have a generic parser for security warnings. 

Similar to the Snyk JSON Parser it should parse a generic vulnerabilities.json with the following keys (severity, description, location? ).

This way a security engineer can add manual findings such as findings from threat modeling, manual code review or pentest findings using a simple json report.

**Comment by fniessink** [comment]
Nice idea. Though wouldn't a CSV format (although I'm not a fan of it) be more logical, seeing that people often use spreadsheets as a poor man's database?

**Comment by bdtesty** [comment]
Lets try both CSV and JSON ? :) 

Ill write a first attempt

**Comment by bdtesty** [comment]
first version JSON now merged: https://github.com/ICTU/quality-time/pull/1566
