### ISSUE TITLE
Snyk Parser should consolidate findings better

### ISSUE THREAD

**Issue by bdtesty** [ICTU/quality-time#1616]
![2020-10-27 13_08_00-Window](https://user-images.githubusercontent.com/8646228/97299711-b2717980-1855-11eb-9f16-7158e2ae2b49.png)

Currently the Snyk parser does not consolidate findings correctly. This results in an enormous amount of warnings. 

The number of warnings should be equal to the number of top-level packages that need to be updated not the total amount of vulnerabilities

**Comment by bdtesty** [comment]
This is what I aim to achieve. Instead of 1211 Security Warnings, It now only shows 4 top level packages that all contain 1211 vulnerabilities sourcing from transitive dependencies.

![2020-10-29 08_59_44-Window](https://user-images.githubusercontent.com/8646228/97541270-2716f600-19c5-11eb-959a-478c949c9dae.png)

For a developer it's easy to review that only 4 packages will need to be updated in order to mitigate 1211 vulnerabilities. 

@fniessink  what do you think ?

**Comment by fniessink** [comment]
I think it's a good idea, and it's similar to how the OWASP dependency check security warnings are reported: per direct dependency the highest severity and the number of vulnerable (direct and indirect) dependencies.

**Comment by bdtesty** [comment]
![2020-11-03 18_53_14-Window](https://user-images.githubusercontent.com/8646228/98022416-e294bb80-1e05-11eb-9837-ee7159dc577b.png)

https://github.com/ICTU/quality-time/pull/1641
