### ISSUE TITLE
Sonarcloud code smells results in 404

### ISSUE THREAD

**Issue by ds-o** [ICTU/quality-time#1672]
When creating a Security Warnings Metric with Sonar as source, I get a 404 when I add "security_hotspot" to the security issues type. Using only "vulnerability" works. The 404 URL is:

https://sonarcloud.io/api/hotspots/search?projectKey=xxx&status=TO_REVIEW&ps=500&branch=master

![image](https://user-images.githubusercontent.com/21058511/99185212-b9025b00-2748-11eb-9213-c5fccac74b7c.png)

**Comment by ds-o** [comment]
The URL should probably be: https://sonarcloud.io/api/issues/search?componentKeys=xxx&resolved=false&ps=500&types=SECURITY_HOTSPOT

**Comment by fniessink** [comment]
What is the version of SonarQube?

**Comment by ds-o** [comment]
It is Sonarcloud.io, im not sure if thats using the same versions and api as SonarQube software.

**Comment by fniessink** [comment]
I see. Unfortunately, SonarSource doesn't tell use which version Sonarcloud.io is (it's continuously updated, they claim).

When I try https://sonarcloud.io/api/issues/search?componentKeys=xxx&resolved=false&ps=500&types=SECURITY_HOTSPOT, but with a SonarQube version 8.3.1 I get: 
```json
{
    "errors":[
        {
            "msg":"Value of parameter 'types' (SECURITY_HOTSPOT) must be one of: [CODE_SMELL, BUG, VULNERABILITY]",
        }
    ]
}
```
The only way, AFAIK, to get hotspots from SonarQube 8.3 and newer is to use the /api/hotspots, which is labeled as an "internal" API by the way. Supporting multiple Sonar versions is a major headache as the API isn't versioned.

**Comment by ds-o** [comment]
As I understand it from the Sonar site, Sonarcloud.io software is similar to SonarQube, but not the same. Perhaps it would be a good idea to support a recent version of SonarQube (as QT already does) and another metric source for Sonarcloud?

Im going to check tomorrow if I see more differences in the Api’s.

**Comment by ds-o** [comment]
In SonarQube I found this (https://next.sonarqube.com/sonarqube/web_api/api/issues):

`'8.2 Security hotspots are no longer returned as type 'SECURITY_HOTSPOT' is not supported anymore, use dedicated api/hotspots`

But in Sonarcloud.io the type is still supported and api/hotspots does not exist:

https://sonarcloud.io/web_api/api/issues

![image](https://user-images.githubusercontent.com/21058511/99410965-5d280580-28f3-11eb-804a-be71700c8dad.png)

Maybe it is easiest to check if the provided URL is sonarcloud.io and use the api/hotspots url in that case?

**Comment by ds-o** [comment]
@fniessink SECURITY_HOTSPOT type is now removed from SonarCloud, only the following is now supported (same as SonarQube already had):

![image](https://user-images.githubusercontent.com/21058511/113508614-58d25100-9551-11eb-8ffa-471d05038170.png)

So I think it is no longer possible to retrieve Hotspots from SonarCloud. SonarQube only supports retrieving Hotspots using the internal API /api/hotspots, but this is not available in SonarCloud.
