### ISSUE TITLE
Export/import of quality reports

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-time#1693]
Allow for exporting/importing quality reports, first version just the reports. #1847 adds measurements.

Exporting the whole history is out of scope. Export includes one report (only the latest copy, the one marked "last: true").

Format: JSON as stored in the database, except for encrypted credentials and an extra top level field for the public key (see below).

Credentials are encrypted individually, using the public key of a Quality-time instance. The user should use the public key of the Quality-time that he or she wants to import the report into. When the user imports the report, Quality-time decrypts the credentials using its private key. Using this approach means that when the public/private key pair of a Quality-time instance changes, exports made earlier can not be imported correctly anymore. The public key used for the export is included in the exported report thus allowing Quality-time to warn the user at import-time when the public key has changed.

Export UI: In the expanded report title add a "Download report as JSON" option that has a text input field for entering the public key of the destination Quality-time. By default this is filled with the public key of the current Quality-time. This is also the way in which users can get the public key of another Quality-time; by simply going to a random existing report and expanding the report title. Default filename contains the report UUID and a ISO-formatted timestamp.

Import UI: On the home page, add a "Import report" button that opens the browser's file import dialog.

Add a new endpoint to the server for importing reports. Users need to be authenticated. Note: there is an existing endpoint for importing example reports that is not automatically suited for this import functionality. All UUIDs in the imported report are replaced with new UUIDs.

Add a new endpoint to the server for exporting reports. Users need to be authenticated to prevent unauthenticated users from faking a destination Quality-time and getting access to all API-credentials. Report UUID is a mandatory argument, public key optional.

Add a new endpoint for retrieving the public key. Users do not need to be authenticated.

Tasks:

1. Server endpoint for export: GET: api/v3/export/<report_uuid> (authentication needed)
1. On startup, the server checks for the presence of a public/private key pair in the database (separate "secrets" collection) and if not present, generates a new public/private key pair
1. Encrypt credentials in exported JSON with the public key and add the public key to the report
1. Release possible/valuable
2. Refactor existing import endpoint to api/v3/import_example_report
1. Server endpoint for import: POST: api/v3/import (authentication needed)
2. Checking that the public in the JSON matches the Quality-time instance's public key. If not, throw error.
2. Decrypt credentials in exported JSON with the private key and insert the report in the database after replacing all UUIDs with new ones.
3. Release possible/valuable
4. Add server endpoint for retrieving public key GET: api/v3/public_key
5. Add and use optional public_key argument to api/v3/export?public_key=<public_key>
3. Release possible/valuable
4. Reconsider adding a UI, maybe API is sufficient to get the business value

**Comment by fniessink** [comment]
The scenario where a user enters a public of another Quality-time instance can be used to get access to the credentials by entering the public key of a public/private key pair the user generated themselves.

**Comment by fniessink** [comment]
@emdv88 If we'll be using cryptography, this may be relevant. If not, it's an interesting read anyway: https://github.com/pyca/cryptography/issues/5771

**Comment by emdv88** [comment]
Definitely interesting. Don't know if we are already using the version 3.4 of cryptography. I did notice a lot of potential error messages during installation and their respective solutions in the FAQs of the docs.

For now it seemed to install fine for me locally as well as in docker containers for the ci environment.

Could this effect production environments only?

**Comment by emdv88** [comment]
On another note, the only reason this branch isn't ready yet is that the feature tests haven't reached 100% coverage yet. 

I wrote the new scenarios, but it seems like the test dataset doesn't contain any passwords, so the encryption part isn't covered.

Where can I edit the dataset that is used during the featuretests?

**Comment by fniessink** [comment]
> On another note, the only reason this branch isn't ready yet is that the feature tests haven't reached 100% coverage yet.
> 
> I wrote the new scenarios, but it seems like the test dataset doesn't contain any passwords, so the encryption part isn't covered.
> 
> Where can I edit the dataset that is used during the featuretests?

There's no precooked dataset, the feature tests create their own data. Some of the [source scenarios](https://github.com/ICTU/quality-time/blob/master/tests/feature_tests/features/source.feature) change credentials.
