### ISSUE TITLE
Grant editing rights to people for specific fields

### ISSUE THREAD

**Issue by cat00man** [ICTU/quality-time#1842]
The ability to grant editing rights to people for specific fields (only Security warning status and Rationale) by adding their username or email address to a new field, editors specific fields, on each individual report.

**Comment by cat00man** [comment]
@fniessink is dit issue nu te zien? Mijn GitHub profiel hebben ze inmiddels unflagged.

**Comment by fniessink** [comment]
Add a second field to the reports overview header: "Users allowed edit measurement entities (user name or email address)". Make sure there is always at least one user with report edit rights. Note the two rights (edit_reports and edit_entities) are disjunct. People who are allowed to edit reports need the edit_entities right to also be allowed to edit entities.

Use the bottle route decorators to configure authentication and permissions:

```python
@bottle.get("/api/v3/some-endpoint", authentication_required=False)  # This means a login is not necessary
def endpoint(...)

@bottle.get("/api/v3/some-endpoint", authentication_required=True)  # This means a login is necessary, but no permissions are required

@bottle.get("/api/v3/some-endpoint", permissions_required="edit_reports")  # This implicitly means that authentication is required, and also that the permission "edit_reports" is required

@bottle.get("/api/v3/some-endpoint", permissions_required=["edit_reports", "edit_entities"])  # This implicitly means that authentication is required, and also that both permissions are required

@bottle.get("/api/v3/some-endpoint")  # This will throw an error (preferably at server start time) because the authentication behaviour is not defined
```

The user rights are stored in the reports_overview. The current "editors" list needs to be changed to a mapping: 
```json
{
   "permissions":
   {
      "edit_reports": ["jadoe", "jodoe"],
      "edit_entities": ["lidoe"]
   }
}
```

Also, the frontend needs to be adapted to hide controls when the user doesn't have the appropriate rights.

Out of scope: 
- Roles. We use rights only for this story.
