### ISSUE TITLE
SonarQube hotspot severities have changed to high/medium/low but Quality-time still uses blocker/critical/major/minor/info

### ISSUE THREAD

**Issue by cat00man** [ICTU/quality-time#1910]
See screenshot.
![AjtAYTTqfp](https://user-images.githubusercontent.com/38661536/107677379-7c3bf680-6c9a-11eb-8810-2c032f6bc644.png)

**Comment by fniessink** [comment]
Add an extra parameter "security hotspot review priority" with values "high", "medium", "low" (check in SonarQube if these are complete) and filter the security hotspots by review priority.

Add an extra column to the security warning entities "Security hotspot review priority" and apply some color.
