### ISSUE TITLE
Postman API and Document

### ISSUE THREAD

**Issue by kargaranamir** [ICTU/quality-time#1983]
I found your project very interesting. I'm Interested in adding other quality measure tools as a collector in this project. like, Understand, PMD, etc.

- Is there any documented developing manual? I found [this ](https://github.com/ICTU/quality-time/blob/master/docs/DEVELOP.md) but it is not comprehensive. 

- also, Is there any postman API schema (or similar tools) for this project or a well-documented APIs List?

**Comment by fniessink** [comment]
Thanks! 

- Unfortunately, the developer documentation is indeed not comprehensive. If you have specific questions and ask them here, we will add the answers to developer documentation.
- We're using the Bottle framework which doesn't generate much documentation unfortunately, but there's a little bit. See the server [README](https://github.com/ICTU/quality-time/blob/master/components/server/README.md).

**Comment by kargaranamir** [comment]
Thanks for your response. and how about this question:
I want to know how I can call each Backend API without delving into the code.
Is there any postman API schema (or similar tools) for this project?
I found a list of API in quality_time_server/API but a Postman schema (or similar tools) helps me more much.

**Comment by fniessink** [comment]
No, there's no Postman API schema. However, to add Understand or PMD as source for Quality-time you won't need to use or know the server API.

**Comment by fniessink** [comment]
Closing this issue for now. Please let us know if you have further questions.
