### ISSUE TITLE
Allow for adding links to Jira/Azure DevOps/GitLab/Trello issues including status of the issue

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-time#2215]
This makes it possible to see in Quality-time what the status of a linked issue us.

UI:
- Allow for configuring multiple issue trackers per Quality-time instance, on the home page. Per issue tracker: Issue tracker type (dropdown with issue tracker types: Jira/Azure DevOps/GitLab/Trello) + Name + URL + credentials.
- Add input fields to metric details for entering an issue: Issue tracker (dropdown with configured issue trackers) + issue id.
- Add column to metric table with "Linked issues". Text of the issue is the issue id. The issue links to the issue in the issue tracker. The status is shown as: 
```jsx
    <Label as='a' color='blue'>
      <a href="http://issue_tracker.example.org/issue-id-123">ISSUE-ID-123</a>
      <Label.Detail>Open</Label.Detail>
    </Label>
```
- The UI loads the statuses of the metrics after (re)loading the report, by asking for the statuses of the issues in the report. 

Server:
- Add API endpoint for synchronously requesting the status of an issue for a specific report uuid.
- Add module for talking to issue trackers, with submodules per issue tracker type.

Data model:
- For each source that is also an issue tracker add a `issue_tracker` object:
```json
  "jira": {
    "name": "Jira",
    "parameters": {},
    "issue_tracker": {
      "help": "How to find the issue id: ..."
     } 
  }
```

Slices:
- Jira first.

**Comment by denniebouman** [comment]
+1

**Comment by emdv88** [comment]
Some thoughts on this issue:
 - Are all possible issue tracker sources sources that provide for the metric "Issues"? (currently azure_devops, jira, anual_number, trello. I guess gitlab could be added to this list) Then we would only need a way to specify if a source parameter is applicable for an issue tracker.
 - Maybe consider making the issue tracker a separate component? That way we make sure that the server doesn't directly talk to external sources. Also, that way the server remains independent of configured sources. Which in turn might make it easier to support custom sources developed by quality-time users.

**Comment by fniessink** [comment]
After demo review:

- One issue tracker per report, configurable via the report header. So the issue tracker configuration at the homepage can be removed.
- This makes it unnecessary to pick an issue tracker per metric. So the issue tracker picker per metric can be removed.
