### ISSUE TITLE
Bring back /api/v3/reports and /api/v3/tagreport to prevent incompatible changes to the API

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-time#2407]
Add back /api/v3/reports. Mark as deprecated and suppress uncovered code.
Add /api/v3/tagreport to `get_report()`

**Comment by eric-nieuwland** [comment]
Check https://stackoverflow.com/questions/13884141/convention-for-http-response-header-to-notify-clients-of-deprecated-api
