### ISSUE TITLE
Security warning status and Rationale disappear from LRK QT

### ISSUE THREAD

**Issue by cat00man** [ICTU/quality-time#2429]
Security warning status and Rationale seems to disappear. On 22-07-2021 both fields were filled in. For example at 22-07-2021 with subject KOT&B app => OWASP ZAP warnings => Warning: CSP: style-src unsafe-inline things were looking like this:
![image](https://user-images.githubusercontent.com/38661536/126949587-1b83815f-e5b0-45da-921e-dc8eb8904d72.png)
And at 26-07-2021 the same subject (after new scans at 24-07-2021 with the same results) it looks like this:
![image](https://user-images.githubusercontent.com/38661536/126949897-6aaa98c1-72d6-4b33-9ba3-6d9d56aef32c.png)

Example with more detail of what's missing:
On 22-07-2021:
![image](https://user-images.githubusercontent.com/38661536/126964334-b65acec2-a5e6-46cc-b675-f33f40d85c72.png)
On 26-07-2021:
![image](https://user-images.githubusercontent.com/38661536/126965207-fc7747ba-77b9-402f-a66e-dd65787fea9f.png)

Can these fields made persistent with recurring warnings?
http://www.quality-time.lrk.ictu/34d9b1f0-c8b3-4689-94d8-23f2ec20dc6b

**Comment by fniessink** [comment]
@cat00man Can you please mail @emdv88 (Erik Verboom) and me the KOTB OWASP ZAP xml file by email? Thanks!

**Comment by cat00man** [comment]
@fniessink and @emdv88, I just emailed this file lr-kotb-OWASP-ZAP-scan.zip to you guys.

**Comment by emdv88** [comment]
Currently the fields "alert", "pluginid", "cweid", "wascid", "sourceid" of a alert type are used to identify an alert type. It seems that in this case the field sourceid changes between runs. Solution could be remove this field from the list of id fields. 

In source_collectors/owasp_zap/security_warnings.py: line 24
