### ISSUE TITLE
Not able to login in 'try it out' setup

### ISSUE THREAD

**Issue by floreseken** [ICTU/quality-time#2565]
I'm following these instructions: https://quality-time.readthedocs.io/en/latest/intro.html#trying-it-out
So basically:

- docker-compose build
- docker-compose up
- try to login

All commands run fine, except for the login part, which gives me:

![image](https://user-images.githubusercontent.com/6927344/131521129-db1c7c7a-cc92-4ee0-88ba-95f967613d8b.png)

At the same time the server logs:

> ldap_1           | 612e3c9f conn=1022 op=4 SRCH attr=objectClasses attributeTypes ldapSyntaxes matchingRules matchingRuleUse dITContentRules dITStructureRules nameForms createTimestamp modifyTimestamp * +
ldap_1           | 612e3c9f conn=1022 op=4 SEARCH RESULT tag=101 err=0 nentries=1 text=
ldap_1           | 612e3c9f conn=1022 op=5 BIND anonymous mech=implicit ssf=0
ldap_1           | 612e3c9f conn=1022 op=5 BIND dn="cn=admin,dc=example,dc=org" method=128
ldap_1           | 612e3c9f conn=1022 op=5 BIND dn="cn=admin,dc=example,dc=org" mech=SIMPLE ssf=0
ldap_1           | 612e3c9f conn=1022 op=5 RESULT tag=97 err=0 text=
ldap_1           | 612e3c9f conn=1022 op=6 SRCH base="" scope=0 deref=3 filter="(objectClass=*)"
ldap_1           | 612e3c9f conn=1022 op=6 SRCH attr=altServer namingContexts supportedControl supportedExtension supportedFeatures supportedCapabilities supportedLdapVersion supportedSASLMechanisms vendorName vendorVersion subschemaSubentry * + +
ldap_1           | 612e3c9f conn=1022 op=6 SEARCH RESULT tag=101 err=0 nentries=1 text=
ldap_1           | 612e3c9f conn=1022 op=7 SRCH base="cn=Subschema" scope=0 deref=3 filter="(objectClass=subschema)"
ldap_1           | 612e3c9f conn=1022 op=7 SRCH attr=objectClasses attributeTypes ldapSyntaxes matchingRules matchingRuleUse dITContentRules dITStructureRules nameForms createTimestamp modifyTimestamp * +
ldap_1           | 612e3c9f conn=1022 op=7 SEARCH RESULT tag=101 err=0 nentries=1 text=
ldap_1           | 612e3c9f conn=1022 op=8 SRCH base="dc=example,dc=org" scope=2 deref=3 filter="(|(uid=admin)(cn=admin))"
ldap_1           | 612e3c9f conn=1022 op=8 SRCH attr=userPassword mail
ldap_1           | 612e3c9f <= mdb_equality_candidates: (cn) not indexed
ldap_1           | 612e3c9f conn=1022 op=8 SEARCH RESULT tag=101 err=0 nentries=0 text=
ldap_1           | 612e3c9f conn=1022 op=9 UNBIND
ldap_1           | 612e3c9f conn=1022 fd=12 closed
server_1         | WARNING:root:LDAP error: list index out of range

I was able to figure out that there is a ldap frontend running at port 3890, at which I can login if I'm using the user DN: _cn=admin,dc=example,dc=org_ and the password _'admin'_

And if I perform a search there for _ObjectClass=*_ this is the result:

![image](https://user-images.githubusercontent.com/6927344/131522765-5d7edbc8-3946-4cb6-b22b-120dba9b9792.png)

I looks like the _admin_ user is some sort of special user that is not found when searching for it.. so also logging in with this user is never gonna work, as the _verify_user_ method basically does the same thing.

If I use one of the other users that can be found, I am able to login in the frontend.

Is this a bug or needs the 'try it out' documentation be updated?

**Comment by fniessink** [comment]
I'm sorry about this. It's indeed a bug, both upstream and in our documentation. The bug upstream, in the osixia/docker-openldap image we use for the test LDAP container is that the admin user has inadvertently been disabled (https://github.com/osixia/docker-openldap/issues/555). You can log in using one of the other users, see: https://quality-time.readthedocs.io/en/latest/software.html#ldap-users. 

I'll clarify the "Trying it out section". Thanks for reporting!
