### ISSUE TITLE
Response time issue with LRK Quality-time

### ISSUE THREAD

**Issue by cat00man** [ICTU/quality-time#2625]
When opening http://www.quality-time.lrk.ictu/34d9b1f0-c8b3-4689-94d8-23f2ec20dc6b in i.e. Google Chrome most of the time I won't get a response from the server:
![image](https://user-images.githubusercontent.com/38661536/134025189-63ae0a17-28ac-4c88-a632-48e4f0f91665.png)

But when I use a Incognito window the response is as expected (within 5 seconds):
![image](https://user-images.githubusercontent.com/38661536/134025629-9a4fc249-30f7-4a39-bb61-d2d5042d5741.png)

**Comment by fniessink** [comment]
I can't reproduce this with Chrome, nor with Safari and Firefox. Can you please open the development tools in your browser and check whether the console log shows anything interesting? If you copy logging here, please remove any sensitive information such as IP-addresses first. Thanks!

**Comment by fniessink** [comment]
Closing due to lack of response.
