### ISSUE TITLE
Two possible issues with the (Outdated) Dependencies metric

### ISSUE THREAD

**Issue by cat00man** [ICTU/quality-time#2761]
Issue one (see image) is that the dependency version of the package used in the subject (eg pp-frontend) is not shown. Colomn *Current version* does not contain the version used.
Issue two (see image) is that sometimes the *Wanted version* of a package is higher then the *Latest version*... That sounds odd.

![image](https://user-images.githubusercontent.com/38661536/138660755-4a626b8e-8043-43ad-a854-a33e034fda69.png)

**Comment by fniessink** [comment]
@cat00man, can you mail me the npm JSON? That is the file you get if you follow the npm link in your screenshot. Thanks.

**Comment by cat00man** [comment]
[npm.json.txt](https://github.com/ICTU/quality-time/files/7409706/npm.json.txt)
Hereby the requested json file.

**Comment by cat00man** [comment]
It seems to have something to do with the npm version you are using. The old version we used produces a json file that does not contain the *Current version* field, but for example in node.js version 16.9 (with npm version 7.21.1) it works well and solves both issues. The latest version of node.js runs in error at LRK, so we don't use it (yet).

![image](https://user-images.githubusercontent.com/38661536/138726442-64d48c24-66f8-4086-984d-34b934de6d9c.png)

**Comment by fniessink** [comment]
OK, that's good to know.

One thought: do you run `npm install` before running `npm outdated`? The [documentation for `npm outdated`](https://docs.npmjs.com/cli/v7/commands/npm-outdated) says (emphasis mine): "This command will check the registry to see if any (or, specific) **installed** packages are currently outdated." 

With respect to why the wanted version can be higher than the latest version: the documentation for `npm outdated` does explicitly mention this.

**Comment by fniessink** [comment]
I've added the Docker command to the docs. Otherwise closing as "works as designed"
