### ISSUE TITLE
Options for issue tracker are ignored when generating a PDF report based on one or more tag(s)

### ISSUE THREAD

**Issue by denniebouman** [ICTU/quality-time#2827]
By generating a PDF report **based on one or more tag(s)**, the options:
- Show how long ago issues were created 
- Show how long ago issues were updated

are ignored (defaults, which are "No" are used).

This "bug" is because the option(s) is an option of the report. A tag report is another (dynamically generated) report that in theory also has that option, but because a tag report is read-only you cannot edit it.

**Comment by fniessink** [comment]
Solution: make the issue tracker options settings that can be changed via the settings panel.

**Comment by fniessink** [comment]
So the issue tracker options are now settings that can be changed via the settings panel, but that doesn't completely solve this bug. The tags reports don't have an issue tracker and hence the issues are always shown in red in the tag reports. Looking into this.
