### ISSUE TITLE
Add a developer role and a quality manager role

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-time#284]
The develop role should be allowed to ignore issues. The quality manager can edit report configurations. Open issue: rights per report?

First version of this will allow for specifying one or more roles the user must have before editing rights are granted.

**Comment by denniebouman** [comment]
+1

**Comment by fniessink** [comment]
How GitLab integrates with LDAP: https://docs.gitlab.com/ee/administration/auth/ldap/
