### ISSUE TITLE
Security warning status and Rationale now partly disappear from LRK QT

### ISSUE THREAD

**Issue by cat00man** [ICTU/quality-time#2852]
Security warning status and Rationale seems to partly disappear now. On 05-11-2021 both fields were filled in for all (7) warnings at the CSH app subject => OWASP ZAP warnings => OWASP ZAP column:
![image](https://user-images.githubusercontent.com/38661536/141431191-55c0a585-c76a-460a-bcf6-7940ce6dd3ad.png)

But ie at 12-11-2021 with the same subject it looks like this (5 unconfirmed warnings and 2 previously marked Won't fix warnings):
![image](https://user-images.githubusercontent.com/38661536/141432074-97e27101-da49-4228-a398-3ec0de4771dc.png)

Seems like #2429 is partly fixed?

**Comment by fniessink** [comment]
Can you mail me the OWASP ZAP report? I don't have access to the workspace where it's located.

**Comment by cat00man** [comment]
[lr-csh-OWASP-ZAP-scan.zip](https://github.com/ICTU/quality-time/files/7536996/lr-csh-OWASP-ZAP-scan.zip)

**Comment by fniessink** [comment]
It seems the `sourceid` is the culprit: the same alert items have different source ids between runs.
