### ISSUE TITLE
Allow for adding a comment to a subject in a quality report

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#2926]
if would be great to be able to be able to toggle the visibility on or off.

**Comment by Sebastiaan127001** [comment]
and that this comment is visible when you export the page as PDF

**Comment by fniessink** [comment]
Tasks:
- Add a comment field to the subject configuration tab, similar to the comment field in the metric configuration tab.
- Show the comment between the subject title and the metrics table as a paragraph of text (html enabled, similar to the comment field).
- Check that the input is properly sanitized, similar to how the metric comment field is checked.
