### ISSUE TITLE
Gravatar is not used by Quality-time

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#2929]
@fniessink my gravatar is not syncing whereas yours does.

**Comment by fniessink** [comment]
I think your email address has not been registered correctly with gravatar.com. This page allows you to check the gravatar for any email address: https://nl.gravatar.com/site/check/

If I fill in my email address it works. If I fill in yours, it doesn't.

**Comment by Sebastiaan127001** [comment]
you were right, issue can be closed
reason: I did not fully understand the workings of the gravatar ui
