### ISSUE TITLE
Usability Issue - anonymous users who open a metric see field that have a blinking cursor

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#2933]
this cursor implies that you can edit it, but instead you can not 
usability-wise, it would be better if this was a greyed out span (without cursor, just visible text)

also in the current situation users get no hint by the tool that they should be logged in, it they don't know they might wonder forever why they cannot edit the value :)

**Comment by fniessink** [comment]
Integer fields should also not show the increase/decrease button when the field is read only.
