### ISSUE TITLE
Support JMeter CSV as source for the 'Slow transactions' metric

### ISSUE THREAD

**Issue by denniebouman** [ICTU/quality-time#2966]
Example CSV: [jmeter.csv](https://github.com/ICTU/quality-time/files/7640930/jmeter.csv)

JMeter docs: https://jmeter.apache.org/usermanual/listeners.html#defaults

**Comment by fniessink** [comment]
@denniebouman, can you mail me a more elaborate example, preferably the XML, JSON, and CSV version of the same performance test?

**Comment by denniebouman** [comment]
@fniessink sure it's in your mail

**Comment by fniessink** [comment]
Todo: use "elapsed" instead of "latency" field to make the results more similar to the results in the JMeter JSON output.
