### ISSUE TITLE
Logged in users cannot modify the violations/warnings status (v3.29.0)

### ISSUE THREAD

**Issue by edvlucas** [ICTU/quality-time#2994]
Reproducing steps:
- Login in QT 3.29.0
- Select an unconfirmed issue (for instance AXE accessibility)
- Expand the issue
- Click on the status input box
  - the input box gets focused and the cursor enabled
- Type in something => nothing changes

The issue started happening after migrating QT from v3.24.0 to v3.29.0. No errors/warnings are displayed in the JavaScript console.

Example:
![image](https://user-images.githubusercontent.com/8328311/145026833-f51ff436-0126-43f4-ac17-0dad69060963.png)

**Comment by fniessink** [comment]
Quality-time has a feature to allow/disallow people from editing measured entities (see https://quality-time.readthedocs.io/en/latest/usage.html#configuring-permissions). Can you check whether the "entity editors" list is empty?

**Comment by edvlucas** [comment]
The report permissions are configured as:
![image](https://user-images.githubusercontent.com/8328311/145211765-372bbdd2-5ae7-4eba-9e1f-3646d7bf1047.png)

I am logged in as admin:
![image](https://user-images.githubusercontent.com/8328311/145211872-073240bf-b631-44d8-86c9-3662ccbdf097.png)

**Comment by fniessink** [comment]
Just to be sure: you can make other changes such as adding a metric or changing a metric comment?

**Comment by edvlucas** [comment]
No, I can't

**Comment by fniessink** [comment]
The frontend sometimes isn't aware that your session is expired. Can you make changes after you log out and log back in again?

**Comment by edvlucas** [comment]
No, unfortunately not

**Comment by fniessink** [comment]
This issue was solved by assigning the correct permissions to people.
