### ISSUE TITLE
403 Forbidden message when configured http URL is redirected to https

### ISSUE THREAD

**Issue by denniebouman** [ICTU/quality-time#3100]
Configuration in Quality-Time:

URL: http://jenkins.project.nl
Authentication: user/pass (basic auth)

Configured URL is redirected (network configuration) to source with http**s** URL
Result: 403, message='Forbidden'

When the http**s** URL is used in the configuration, everything works OK

**Comment by fniessink** [comment]
Because it's unclear why this happens and the work-around is simple (just change the http://jenkins... to https://jenkins...) we won't investigate further.
