### ISSUE TITLE
Connection error when trying to get the Checkmarx CxSAST version

### ISSUE THREAD

**Issue by cat00man** [ICTU/quality-time#3118]
Connection error when trying to get the Checkmarx CxSAST version from https://checkmarx...:

`Connection error
403, message='Forbidden', url=URL('https://checkmarx.../cxrestapi/sast/engineServers')`

When using same username and password in a webbrowser for the CheckMarx webclient it works fine.

**Comment by fniessink** [comment]
Can you please double check the credentials for the Checkmarx source configured for the version metric? 

The other metrics using Checkmarx in your report don't seem to have this problem. Also, it works for me, tested from a local Quality-time instance and from an Eco1 Quality-time instance.

**Comment by cat00man** [comment]
Double checked, got a "URL connection OK" message but after that still "Connection error". Same credentials work in rest of Quality-time and in browser connecting to Checkmarx UI. So shoot me but lek....

**Comment by fniessink** [comment]
Maybe the automation user doesn't have permission to check the version? I'll make a copy of the version metric and configure it with a different Checkmarx user to see if that makes a difference. Can you give me temp report edit permissions?

**Comment by fniessink** [comment]
Closing this issue as we're phasing out Checkmarx.
