### ISSUE TITLE
Highlight metrics to make it easier to discuss specific metrics in an online meeting

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#3132]
Show a metric ID and maintain that ID, no matter the sorting.
This helps when discussing the report.

Suggestion:

![image](https://user-images.githubusercontent.com/95095453/147828709-8bdf884a-f48d-4957-8c88-72af23f760e0.png)

**Comment by Sebastiaan127001** [comment]
I forgot to mention. If this will be implemented. It should initially be clear that the column sorting is by ID. So when a board is opened, it will show a little triangle (arrow) pointing downwards to indicate this sorting.

**Comment by fniessink** [comment]
Metrics can be reordered. Would you expect the id's to be regenerated after reordering?

**Comment by Sebastiaan127001** [comment]
I expect the ID's to be fixed to a metric, it's the identification of a metric (not a row number). So ordering by status will shift the order of the ID's, making that list non-chronological.

**Comment by fniessink** [comment]
We think an extra column is rather costly in terms of UI-space, adding numbers or ids that provide hardly any informational value. So we have been looking at alternative solutions:

1. If the purpose of this feature request is to draw attention to a specific metric when discussing the quality report in an online meeting, we think other options may be better. For example, highlight the table row when hovering over it or when clicking it.  
2. If the purpose is to make sure each metric has a unique name, you can already do that yourself by changing the metric name in the metric configuration tab.

What do you think?

**Comment by fniessink** [comment]
We'll implement option 1.
