### ISSUE TITLE
It is possible that the user self-upvotes

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#3136]
A user can currently give an upvote to him- or herself. A user needs two upvotes from two different users other than him- or herself.

**Comment by fniessink** [comment]
There's no upvoting in Quality-time itself. This is about GitLab I assume. Are you suggesting that Quality-time should check whether people upvoted their own merge requests in GitLab and if so, disregard that upvote?

**Comment by Sebastiaan127001** [comment]
Excuse me for being incomplete. Yes, this is what I meant. Developers in one of the projects have found a way to omit this check :)

**Comment by fniessink** [comment]
This is a limitation of the community edition of GitLab. By upgrading to the Premium version of GitLab you get the ability to have a more formal approval process of merge requests. Also, we have no way of knowing whether the creator of the merge request is equal to the person have done most of the work that is part of the merge request. So, it might be perfectly fine if someone upvotes their "own" merge request.
