### ISSUE TITLE
Move last report update date/time to top of the report

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#3156]
When (automatic) printing, the generated PDF shows a fixed moment in time, like a snapshot.
The moment of the snapshot (is the time of generating/printing) is in my opinion hidden in the black footer at the bottom.
For me, it would be more user-friendly if the date was also available in the title.

Add a block to the top of the page containing:
- Add header: "About this report"
- Title of the report: "<Title> <subtitle>", links to the Quality-time report
- Date of the report: "Report date: <date>"
- Date and time of the export: "Generated: <date/time>
- Quality-time version: "Quality-time version: x.y.z", links to the changelog of the Quality-time version.

Also remove the footer from the exported PDF.

**Comment by fniessink** [comment]
Add the time in the footer to the report title as well, using `@media print {...}` CSS. Position the text "Report date: $(date)" to the righthand side of the page on the same height as the report title. Make sure the date is localised. Make sure that time travel works, i.e. that the correct report date is also printed when the report is not from today.

**Comment by Sebastiaan127001** [comment]
%VOTE
