### ISSUE TITLE
Allow for user to change to dark mode layout

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#3159]
Open issues:
- [x] Listen for changes to preferred mode (https://stackoverflow.com/questions/56393880/how-do-i-detect-dark-mode-using-javascript)
- [x] Date picker dark mode => won't do for now.

**Comment by Sebastiaan127001** [comment]
This is more convenient for the eyes and could save energy on some displays :)

**Comment by Sebastiaan127001** [comment]
maybe a toggle like this in the top right of the black header bar 
https://dev.to/joyshaheb/light-dark-mode-toggle-button-using-1-variable-2021-css-js-13l

**Comment by Sebastiaan127001** [comment]
see also this link for more info https://ryanfeigenbaum.com/dark-mode/

**Comment by fniessink** [comment]
I have looked into this a bit, but unfortunately Semantic UI React doesn't support this out of the box so it's not trivial to implement.

Most if not all Semantic UI React components have an`inverted` property that we can use. Dark/light mode can be a React context. We should look at the user preference specified in the OS settings if no dark or light mode is explicitly selected.

**Comment by Sebastiaan127001** [comment]
I have reviewed v3.34.0-rc.2.
This is already a very complete layout. Maybe some minor enhancement suggestions.
If I read through this [page](https://css-tricks.com/a-complete-guide-to-dark-mode-on-the-web/) as a guideline and walk through each advice, I see the following.

- [x] The white parts are too white to my opinion. According to the above article these should be off-white, like #121212 .


- [x] The text in the middle of the pie charts at the top are not so readable.
![image](https://user-images.githubusercontent.com/95095453/157235985-bbe732c1-7696-4136-a011-dd27ba149fd3.png)

- [x] Furthermore, the red alerts when a source is not working could be more readable.
![image](https://user-images.githubusercontent.com/95095453/157252004-1e1ed7c4-5ad0-45d5-9905-33c5b6a80c67.png)

- [x] Did it pass the AXE core contrast ratio test?

**Comment by fniessink** [comment]
> The white parts are too white to my opinion.

Do you mean the white parts of the donut charts or the white texts?
