### ISSUE TITLE
Allow for users to filter by metric status

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#3160]
It is already possible to filter by tags.
It will help create a quick overview of metrics that require attention if the user could filter by the metric status, like:
- show all metrics in the 'near target' state (YELLOW)
- show all metrics in the 'above target' state (RED)

It should also be possible to select both at the same time, having yellow and red states displayed all together (and hiding the green and grey and white states)

**Comment by fniessink** [comment]
The hamburger menu allows you to only show "metrics requiring action", i.e. yellow and red metrics. Is that sufficient?

**Comment by Sebastiaan127001** [comment]
I believe this functionality meets the needs for now. It's only that this hamburger menu is not very intuitive because, partly because of its placement. This is the reason why I did not find it. But I believe that requires a different feature request :) .

**Comment by Sebastiaan127001** [comment]
A quick fix would be replacing the hamburger icon for a cogwheel.

**Comment by Sebastiaan127001** [comment]
Moreover, it would be great if the user could trigger this for the complete report at once.

**Comment by fniessink** [comment]
> Moreover, it would be great if the user could trigger this for the complete report at once.

That is what "Hide metrics not requiring action" does: it hides all metrics in the report that don't require action.
