### ISSUE TITLE
Make it easier to see when something was changed in Quality-time

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#3167]
The changelog provides an overview all changes, but often one simply wants to see when a specific comment, target, or measurement entity (violation, security warning, etc.) status was last changed and by whom.

**Comment by fniessink** [comment]
Changing the rationale adds a change in the change log of the source, including who made the change and when. Isn't that what you're asking for?

**Comment by fniessink** [comment]
There are also changelog per subject, per metric, and per source. Isn't that enough to give you the insight you want?

**Comment by Sebastiaan127001** [comment]
Can be closed, this need will be fulfilled by https://github.com/ICTU/quality-time/issues/3354
