### ISSUE TITLE
Allow for QT to detect the Gitlab version

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#3168]
Some metrics of GitLab require the premium/ Enterprise edition.

It would be useful if QT detects the type of GitLab currently used and allows and disallows certain metrics.
When it does not allow, it should always notify the user of this and why.

![image](https://user-images.githubusercontent.com/95095453/148073611-e6486691-42ad-4319-bf41-61c5a94e7174.png)

**Comment by fniessink** [comment]
As you can simply check in GitLab once whether you have the premium version or not I don't see the added value of having Quality-time do this for you. Also, Quality-time can't "disallow" you to add certain metric types as it doesn't know what kind of GitLab you have before you add the source to the metric. Even if you add a GitLab OSS as source to one metric, that doesn't mean you don't have another GitLab instance that is the Premium version that you want to add as source for another metric.
