### ISSUE TITLE
Improve the status text in the tooltip

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#3171]
It would be convenient for the end-user if QT uses unambiguous, self-explanatory texts.
The text in the tooltips of each metric can be improved.

1. The text "Last measured" can be confused with a source measuring something. In case QT could not fetch anything, like in the attached image, this should be "last data retrieval attempt".
2. The text "First measured" could be interpreted as the moment when QT started measuring this, where it means to say: "last change of value".

![image](https://user-images.githubusercontent.com/95095453/148223925-71910d4a-98f1-44b5-a266-bb0b4f15cbd2.png)

**Comment by fniessink** [comment]
1. "This metric was last measured ..." or "Last measurement attempt ..." if the measurement failed.
2. "This value was first measured ..." or "Value unknown since ..." if the measurement failed.
