### ISSUE TITLE
Allow for selecting 1 day as trend interval

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#3182]
At the moment, it is not possible to compare today with yesterday.

This feature would make this easier.

![image](https://user-images.githubusercontent.com/95095453/148441532-9a89cd3a-1b43-4b4b-a8c1-44110c7628d9.png)

**Comment by fniessink** [comment]
Tasks:
- Add the option "1 day" to the "Time between dates" menu. 
- Change the `trendTableInterval` unit to be days instead of weeks.
- Add a unit test to `TrendTable.test.js` that column dates are 'calculated' correctly when using the 1 day interval.
