### ISSUE TITLE
More flexible searching for source files in Gatling output folder

### ISSUE THREAD

**Issue by denniebouman** [ICTU/quality-time#3226]
Hereby the request to search more flexibly within the zip for the Gatling output for the desired source files for the different Gatling Performance Metrics. In this way it is possible to use e.g. date/time in the output folders.

**Comment by fniessink** [comment]
@denniebouman, please copy the Quality-time error message you currently get here. Thanks!

Open questions:
- Does the GitLab CI zip file have a .zip file extension?
- How can we see (before manipulating the `api_url` below) that the URL points to a zip file?

```python
class GatlingJSONCollector(JSONFileSourceCollector):
    """Base class for Gatling collectors that read the stats.json file."""

    async def _api_url(self) -> URL:
        """Extend to translate the HTML URL into a URL to the stats.json file."""
        api_url = await super()._api_url()
        api_url.removesuffix("/index.html")
        return URL(api_url + "/js/stats.json")
```

**Comment by denniebouman** [comment]
@fniessink Error Message:

Connection error
404, message='Not Found', url=URL('https://gitlab.project.org.nl/project/-/jobs/artifacts/branch/download?job=docker:performance-reports/js/stats.json')

**Comment by denniebouman** [comment]
@fniessink 
Hi Frank,

Open questions:
_Does the GitLab CI zip file have a .zip file extension?_ 
-> answer: Yes!

_How can we see (before manipulating the api_url below) that the URL points to a zip file?_
-> answer: I think the easiest solution is to check if there is a “download” present in the URL. When the URL contains “download”, it downloads the archive (zip). When the URL doesn’t contain “download” it downloads a specific file:
https://docs.gitlab.com/ee/api/job_artifacts.html

Download the artifacts **archive**:
GET /projects/:id/jobs/artifacts/:ref_name/**download**?job=name

Download a single artifact **file** by job ID:
GET /projects/:id/jobs/:job_id/artifacts/*artifact_path

Download a single artifact **file** from specific tag or branch:
GET /projects/:id/jobs/artifacts/:ref_name/raw/*artifact_path?job=name

**Comment by fniessink** [comment]
Instead of manipulating the URL before downloading the information, first retrieve the URL and check whether the result is a zip file. If not, then add the `/js/stats.json` and try again.
