### ISSUE TITLE
Issue Identifier can be entered when there is no issue tracker configured.

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#3228]
When editing a metric, the user can enter an issue identifier.
But when there is no Issue Tracker configured at the top of the report, the interface still allows entering an issue id.
This should not be possible and the users should get a proper message when he/she tries to fill the field of the issue id.

**Comment by fniessink** [comment]
I don't agree it shouldn't be possible to enter an issue id without having an issue tracker configured. That just means you need to enter the id in the comments so as not to forget it and then move it to the issue id field after having configured the issue tracker. However, I do agree it's a good idea to warn the user more clearly that there's no issue tracker configured.

**Comment by fniessink** [comment]
Add an error message to the link input field (cf. https://react.semantic-ui.com/collections/form/#states-error) if no issue tracker is configured, saying (title) "No issue tracker configured", (content) "Please expand the title of this report and configure an issue tracker in the issue tracker tab."

Show the issue in the issue column, even when there is no issue tracker configured, using a red background (like for sources that have failed).
