### ISSUE TITLE
Improve Trend Graph

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#3302]
1. add a legend that describes the areas, like the grey area
2. add ability to pan and zoom the way it is demonstrated here https://canvasjs.com/react-charts/chart-zoom-pan/ . By adding this, users can more easily zoom in on a period to better see what the trend was for the last week or so.
3. add the feature to touch a point on the graph with the mouse pointer that will show a dot with the exact values. Just like the graph on the page mentioned at point 2.
4. optionally: make the graph look more natural / more smooth, the current theme looks a little blockish (8 bit).

![image](https://user-images.githubusercontent.com/95095453/150750796-214d10f1-a643-42db-8b31-02cf9d6ce23a.png)

**Comment by Sebastiaan127001** [comment]
@fniessink I also would like this one to be implemented, does this need to be split into sub-issues?

**Comment by fniessink** [comment]
Yes, please.

**Comment by Sebastiaan127001** [comment]
https://github.com/ICTU/quality-time/issues/3587

**Comment by Sebastiaan127001** [comment]
https://github.com/ICTU/quality-time/issues/3586

**Comment by Sebastiaan127001** [comment]
https://github.com/ICTU/quality-time/issues/3588
