### ISSUE TITLE
Allow for user to add technical debt to individual violations

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#3332]
For instance, when there are unmerged branches and the team promised to fix it in two weeks, it would be useful to add technical debt to a specific branch. This can only be done for metrics with violations that can be isolated and identified.

![image](https://user-images.githubusercontent.com/95095453/151439131-573cfbe5-10fa-4a5b-97bf-7a5904f19358.png)

**Comment by fniessink** [comment]
Rename the status "Resolve as fixed" to "Resolve as will be fixed" and change the description from "This [entity] has been fixed and will disappear shortly" to "This <entity> will be fixed and should disappear shortly."

Add an end date attribute to the entity that can be entered regardless of what the entity status is. Label: "[Entity] status end date". Help popup: "Consider the status of this entity to be "Unconfirmed" after the selected date."

The measurement entities get an extra attribute "status_end_date", e.g.:

```json
{
  "entity_user_data": {
      "AXellfukmoRlpKCRHShW": {
          "status": "fixed",
          "status_end_date": "2022-02-28T00:00"
      }
  }
}
```

To update the status and measurement value of the metric we use the same mechanism as used for technical debt end date. Change this function in `components/server/src/shared/model/source.py`:

```python
    def _entities_to_ignore(self) -> Sequence[dict[str, str]]:
        """Return the entities to ignore."""
        statuses_to_ignore = ("fixed", "false_positive", "wont_fix")
        user_data = self.get("entity_user_data", {})
        entities = self.get("entities", [])
        return [entity for entity in entities if user_data.get(entity["key"], {}).get("status") in statuses_to_ignore]
```

to also look at the `status_end_date`.
