### ISSUE TITLE
Improve Issue Identifier field functionality

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#3367]
Currently, there are a few issues with the Issue Identifier, the field where the user can link metrics to one or more issues from the issue tracker.
![image](https://user-images.githubusercontent.com/95095453/152191476-c2cad3b9-03b3-47da-a91a-bf097630a1cb.png)

Issues:
- When a value is entered and the user waits, the value disappears after a while. This is not useful and gives the user too little time to think.
- When a value is entered and the user leaves the field, the value disappears because the user needs to click "add". This feature is different from the functioning of all other fields, which are automatically saved when leaving the field.

Improvement suggestions:
- When a value is entered in the field, the user gets suggestions, just like this happens in JIRA
![image](https://user-images.githubusercontent.com/95095453/152192472-cf9bfeaa-10c4-4eb8-81a4-cc6c08e13bcc.png)

- Maybe also add an auto-complete function, just like other fields. For instance, with the prefix.

**Comment by fniessink** [comment]
@Sebastiaan127001 Please split this issue in two different bug reports and one feature request.

**Comment by Sebastiaan127001** [comment]
@fniessink  I have split it into 3 issues. 
https://github.com/ICTU/quality-time/issues/3561
https://github.com/ICTU/quality-time/issues/3560
https://github.com/ICTU/quality-time/issues/3559

**Comment by fniessink** [comment]
Thanks.
