### ISSUE TITLE
Allow for users to see the name of the related issue.

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#3368]
It would be useful to add the title or part of it in the user interface of QT.
As of this moment, the user can only see the issue number and status.
Suggestion: if it does not fit, it can be expandable on hover, or with a tooltip.,
![image](https://user-images.githubusercontent.com/95095453/152193276-2a4d61ea-5a12-41de-853b-b9c1a09fe20e.png)

**Comment by fniessink** [comment]
There was a reason why this wasn't implemented with the original feature, but I can't remember what it was off the top of my head. @emdv88, do you remember?

**Comment by fniessink** [comment]
Add the summary field to the popup. Make it configurable whether the summary is also shown in the issue column in the metric table.
