### ISSUE TITLE
Suggestion: change button names move and copy

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#3431]
Problem: it's hard to understand the function of the move and copy buttons at first notice
Possible solution: For the purpose of clarification, change the names of the buttons move and copy respectively to "move to here" and "copy to here".

**Comment by fniessink** [comment]
When hovering above the buttons, popups are shown explaining what the add, move, and copy buttons do. Given that, I don't see the added value of adding "here" to every add, move, and copy button.
