### ISSUE TITLE
GitLab job artifact archive download is not recognized as zip

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-time#3478]
Add a check for the `Content-Disposition` header in `__is_zip`. Example value: `attachment; filename="gatling.zip"; filename*=UTF-8''gatling.zip`

**Comment by wkoot** [comment]
In version 18 of GitLab, this is failing again:
* [ ] Solve for `gitlab/api/v4/projects/[project-id]/jobs/artifacts/[branch-name]/download` urlpath
