### ISSUE TITLE
Issue identifier suggestions from Jira

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#3561]
![image](https://user-images.githubusercontent.com/95095453/152191476-c2cad3b9-03b3-47da-a91a-bf097630a1cb.png)

Improvement suggestions:
- When a value is entered in the field, the user gets suggestions, just like this happens in JIRA
![image](https://user-images.githubusercontent.com/95095453/152192472-cf9bfeaa-10c4-4eb8-81a4-cc6c08e13bcc.png)

- Maybe also add an auto-complete function, just like other fields. For instance, with the prefix.

**Comment by Sebastiaan127001** [comment]
https://github.com/ICTU/quality-time/issues/3367

**Comment by fniessink** [comment]
Jira has an endpoint to [get issue picker resources](https://docs.atlassian.com/software/jira/docs/api/REST/8.22.1/#issue-getIssuePickerResource) that can be used to get issue information based on the search query that user enters. 

The frontend uses a server endpoint to get the suggestions from Jira (using the issue tracker URL and credentials) and adds the results of the call to the options of the MultipleChoiceInput. The Jira endpoint has one argument: the query string.

- [x] Currently, the MultipleChoiceInput field accepts a static list of options, replace this with possibility to pass a `get_options` function that takes the searchQuery as argument and returns the options. Replace existing uses of the options argument with `() => ["a", "b", "c"]`.
- [x] Create new external server endpoint to get issue id suggestions (we don't have the issue tracker credentials in the front end so can't get the suggestions directly).
- [x] Use the suggestions endpoint.
- [x] To render the options, a render_option() function can be passed that is responsible for rendering one option. If no render_option() function is passed, assume each option is a string.
