### ISSUE TITLE
Use release version of Fomantic UI CSS when available

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-time#3575]
The [current version of Fomantic UI CSS](https://www.npmjs.com/package/fomantic-ui-css) (2.8.8) has an [extra semicolon](https://github.com/fomantic/Fomantic-UI/issues/2027) which makes it incompatible with Webpack 5, which in turn prevents an upgrade to Create React App v5.0. 

We use https://github.com/peacekeeper/Fomantic-UI-CSS.git#c94ff9bd5ab897cd3e3facd2c968090da8755dcb which contains a fixed version of Fomantic UI CSS. 

When Fomantic UI CSS >2.8.8 has been released, we can change the dependency to use the released version of Formantic UI CSS at https://github.com/fomantic/Fomantic-UI-CSS

**Comment by lubber-de** [comment]
Fomantic-UI 2.9.0 was just released
