### ISSUE TITLE
When VPN connection drops no error occurs

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#3580]
When accessing QT over a VPN and the connection is suddenly broken, QT still appears to be functioning, but it cannot update any field anymore without telling the user why.

**Comment by Sebastiaan127001** [comment]
![image](https://user-images.githubusercontent.com/95095453/159788761-8bd7582b-ef2f-46ef-adf8-dfa609e4ff7d.png)

**Comment by Sebastiaan127001** [comment]
https://user-images.githubusercontent.com/95095453/159788930-7a503ff9-2f06-4bc0-97c2-10033ac6e796.mov

**Comment by fniessink** [comment]
Not all usages of `fetch_server_api` have a catch exception handler. Check if we can add a generic `.catch` to the `fetch` call in `fetch_server_api` in `components/frontend/src/api/fetch_server_api.js`.
