### ISSUE TITLE
When displaying multiple dates, also apply this to the dashboard cards

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#3583]
When enabling trend view with multiple dates, the dashboard cards should also display multiple charts, showing the summary for that card on each date.

**Comment by fniessink** [comment]
If multiple dates are visible, replace the donut chart with a stacked column graph, one column per date. The order of the dates should reflect the order of the dates in the metric tables.

**Comment by fniessink** [comment]
Blocked by #3722.
