### ISSUE TITLE
Make requests with ERROR status also visible in QT for metrics with Gatling as source

### ISSUE THREAD

**Issue by denniebouman** [ICTU/quality-time#3660]
When an error occurs for requests/simulations with Gatling as source, these ERROR's are not visible (yet) in Quality-Time. The ERROR's are logged in the simulation.log file. 

Feature request: add support for these ERROR's for:
- Metric Type Tests
- Source Type: Gatling
- Test results: error (in addition to failed and success)

**Comment by fniessink** [comment]
I have been looking into this, but there are some problems/challenges:

- [The Gatling lead developer considers](https://groups.google.com/d/msg/gatling/QfA0RrV2W_Q/4tzDAe2YAgAJ) the simulation.log format an implementation detail, subject to frequent changes.
- Hence, I haven't been able to find good documentation of the format. There's a [simulation.log parser](https://github.com/nuxeo/gatling-report/tree/master/src/main/java/org/nuxeo/tools/gatling/report), but it doesn't deal with ERRORs.

So, I'm not sure how to interpret lines with ERRORs. If an ERROR occurs for a transaction, has the whole transaction failed? Or can it still partly succeed?

Also, I've got the impression that multiple ERRORs can occur per transaction, so should repeated ERRORs for the same transaction be ignored?

**Comment by fniessink** [comment]
Workaround: count the total number of transactions using the 'tests' metric and set a minimum number of expected tests.
