### ISSUE TITLE
Add a dropdown menu to add-buttons allowing the user to select the item type

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-time#3718]
Buttons:
- [x] Add subject
- [x] Add metric
- [x] Add source

Other:
- [x] Add subtype descriptions to dropdown menus
- [x] Limit available options to container type
    - [x] Metrics
    - [x] Sources
- [x] Make long dropdown menus searchable
- [x] Change docs
- [x] Change screenshots
- [x] Metrics no longer have "default" sources. 
    - [x] Remove from docs.
    - [x] Consider removing "default" sources from the data model.

**Comment by Sebastiaan127001** [comment]
@fniessink great addition!
