### ISSUE TITLE
Add Harbor (with Trivy as scanner) as a supported source 

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#3729]
Refs:
- https://github.com/goharbor/pluggable-scanner-spec

**Comment by fniessink** [comment]
This needs a spike to find out how Quality-time can read the SAFIR output produced by Trivy through Harbor. Either use a Harbor instance at one of our projects or install Harbor locally.

**Comment by Sebastiaan127001** [comment]
%VOTE

**Comment by fniessink** [comment]
@Sebastiaan127001 Can we use a Harbor instance at one of your projects to do a spike? We only need read-only access.

**Comment by Sebastiaan127001** [comment]
not sure if there is an accessible harbor instance from our QT env.
let's discuss in a call

**Comment by fniessink** [comment]
There seems to be little documentation on the Harbor API. The advice is to use the Swagger docs on a running instance. The swagger.yaml lives here: https://github.com/goharbor/harbor/blob/main/api/v2.0/swagger.yaml.

There's a demo server at: https://goharbor.io/docs/edge/install-config/demo-server/

The `/projects/{project_name}/repositories/{repository_name}/artifacts` endpoint with the parameter `with_scan_overview=true` includes a scan overview in the response:

```json
    "scan_overview": {
      "application/vnd.security.vulnerability.report; version=1.1": {
        "complete_percent": 100,
        "duration": 9,
        "end_time": "2023-02-15T06:55:10.000Z",
        "report_id": "cafcda51-0b0c-4208-a5cf-80188aaf68b8",
        "scan_status": "Success",
        "scanner": {
          "name": "Trivy",
          "vendor": "Aqua Security",
          "version": "v0.35.0"
        },
        "severity": "None",
        "start_time": "2023-02-15T06:55:01.000Z",
        "summary": {
          "fixable": 0,
          "summary": {},
          "total": 0
        }
      }
    }
```

The `/projects` endpoint lists all projects and the `/projects/{project_name}/repositories` endpoint lists all repositories for a project. There's also a `/repositories` endpoint to get all repo's.

**Comment by fniessink** [comment]
Development currently paused. De Harbor demo https://demo.goharbor.io/harbor/projects has no scans at the moment.
