### ISSUE TITLE
Scalability metric does not accept 100%

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#3787]
The metric scalability with source performance test runner does not accept 100% as a value.
The [manual](https://github.com/ICTU/performancetest-runner/wiki/Evaluation-of-testresults:-5-steps#step-5-to-what-level-can-the-application-be-overloaded-stress) states that 100% means that no breaking point has been detected.

Therefore, this metric should accept 100% as a value.
Furthermore, the default metric unit is "users" where it should be "test duration".

The scalability value returns the percentage of the total test duration where the response times and the error rate start to increase.

**Comment by fniessink** [comment]
> Furthermore, the default metric unit is "users" where it should be "test duration".

That's not what the docs of the Performancetest-runner say, see https://github.com/ICTU/performancetest-runner/wiki/Metrics#trendbreak-scalability--stress-testing
