### ISSUE TITLE
Allow for using a GitLab CI-pipeline as source for the 'source up-to-dateness' metric

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-time#3927]
GitLab already supports the source-up-to-dateness metric for files in GitLab. Use the same solution as for Azure DevOps: present both file path and pipeline parameters to the user and indicate in the tooltip that files get preference.

Note: Jenkins and Azure DevOps don't need to be changed. In case of Jenkins the source up-to-dateness of jobs can be measured (job artifacts have the same date, so no need to configure artifacts separately). In case of Azure DevOps Quality-time already supports both files and pipelines.

Reported by @Sebastiaan127001

**Comment by Sebastiaan127001** [comment]
%VOTE
