### ISSUE TITLE
Download report as pdf doesn't work anymore

### ISSUE THREAD

**Issue by cat00man** [ICTU/quality-time#3932]
Clicking the button (Download report as pdf) in the (LRK => http://www.quality-time.project.example/34d9b1f0-c8b3-4689-94d8-23f2ec20dc6b) report results in a nearly empty pdf. 
[Kwaliteit-Release-Package-LR-GIR-KO.pdf](https://github.com/ICTU/quality-time/files/8803090/Kwaliteit-Release-Package-LR-GIR-KO.pdf)

Also using curl it doesn't produce a report as it did in the beginning of May. 

Possible time out issue while generating the (large) report?!?

**Comment by fniessink** [comment]
The renderer component was changed recently, May 16 (https://quality-time.readthedocs.io/en/latest/changelog.html#id3), that may be the cause of this.

I managed to download a complete PDF via the UI once. The next few times it failed.
