### ISSUE TITLE
Change Input Field Labels dynamically to indicate colour change

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#4064]
The thresholds that trigger the change of colour can be confusing to set.

When I set the metric direction, the labels of target and near target should change so that it's clear for the user what will happen when, eg: (when the value is 1000 or above the metric will colour red).

![image](https://user-images.githubusercontent.com/95095453/174614912-4bad44d1-0627-4b21-bc6a-a1ae71360128.png)

An alternative solution (better imho) would be a visual slider with colours.

**Comment by fniessink** [comment]
Add a popup to the "Metric target", "Metric near target", and "Accepted technical debt" that illustrates the values using a simple horizontal stacked bar chart, e.g.:

```
       25 violations    50 violations
====green=====|====yellow====|=====red=====
```
