### ISSUE TITLE
Change the default value for Size (LOC) to up-to-date standard.

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#4066]
According to the latest report of SIG, the value should be around 300k instead of 30k.

**Comment by fniessink** [comment]
The SIG target is for complete applications. The size metric can be used to measure applications and components. Since we don't know what the user is going to measure it's better to have a default value that's too low than too high.

**Comment by Sebastiaan127001** [comment]
so what is the rationale for 30k as a default then? Can we add to the informative pop-up that SIG suggests 300k as a max for complete applications?

**Comment by fniessink** [comment]
No specific rationale, other than that it forces the user to make a conscious decision about what the target should be much earlier than when we set the default at 300K. 

What we could maybe implement, when we have different subject types for application and components, is default targets that differ per subject type. Then the default target for applications could be 300K and for components something much smaller. But I'm not sure that's worth the trouble.
