### ISSUE TITLE
Monitor the quality of the quality management

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#4069]
# Epic

As a quality manager I want to report on the timeliness of actions in response to metrics not meeting their targets so I can show to management and clients that the quality management process is functioning adequately even if metrics themselves may not be meeting all their targets at a specific moment in time.

## Acceptance criteria

- [x] I can report on the timeliness of responding to metrics becoming red/yellow/white

## Open issues

- Since Quality-time so far only reports on the value of metrics at a specific moment in time (as opposed to averages/trends over a period of time) we need to think about how to visualize this. By first doing #4190 we hopefully get a better idea of options.
- The period of time to report can be a configuration option of the report, a setting in the settings panel, or we can use the time period determined by the combination of the number of dates and the time between dates.

## Out of scope

- Note that the desired reaction times are stored in the report, so while it is possible to change the desired reaction times, this has no effect when time traveling to a historic version of the report.

# User stories

- #4190
- #4538

**Comment by Sebastiaan127001** [comment]
%VOTE

**Comment by fniessink** [comment]
This issue is replaced by #4190.

**Comment by Sebastiaan127001** [comment]
The new report should answer:
Within the set period, did the development team respond to yellow and red metrics, from a subset of metrics, within the desired reaction times?
