### ISSUE TITLE
Ability to customise the out-dated time per metric

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#4096]
In relation to https://github.com/ICTU/quality-time/issues/4075

**Is your feature request related to a problem? Please describe.**
Some metrics have sources that do not update every hour.
The problem is that QT will show this info as outdated, while it can be still up-to-date if it has been confirmed with the team as a way of working.

**Describe the solution you'd like**
I would like to have a field at the source configuration, where one can adjust the default outdated time to a custom set time.

**Describe alternatives you've considered**
accepting the metrics to turn white?

**Additional context**
n/a

**Comment by fniessink** [comment]
If this in relation to the GitLab artifacts issue: we're going to solve that in a different way (by changing the interaction with the GitLab API). Otherwise, I don't understand the requested feature.

**Comment by fniessink** [comment]
This is not needed: 
- If Quality-time is broken, the UI will warn the user that the most recent measurement is old en tell them to contact a system admin.
- If the source is not available, Quality-time will show the source as missing within 15 minutes.
- To see that the data in the source is outdated, the user should use the "source up-to-dateness" metric.
