### ISSUE TITLE
When adding a new metric, the cursor should focus

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#4114]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I click 'add metric' and start typing and nothing happens.

**Describe the solution you'd like**
When clicking the 'add metric' the text cursor should jump to the input field so that the user can start typing right away, without any further click.

**Describe alternatives you've considered**
shift tab did not work

**Additional context**
![image](https://user-images.githubusercontent.com/95095453/176589298-a017bba2-c787-4937-8be9-a9fa50309fea.png)

**Comment by fniessink** [comment]
Did you try "tab"? That works for me in Safari. 

Still think it's a good idea to give keyboard focus to the input right away, though.

**Comment by Sebastiaan127001** [comment]
tab does not work in chrome (for this)

**Comment by Sebastiaan127001** [comment]
@fniessink this implementation is nearly finished. Now you can start typing right away, but you do not see a blinking cursor unless you click the field. Let's discuss how to improve this.
