### ISSUE TITLE
Support multiple LDAP servers

### ISSUE THREAD

**Issue by jordivandermeer** [ICTU/quality-time#4141]
For high availability purposes I would like to be able to configure multiple LDAP backend servers.
If the first ldap server is down QT should automatically select a secondary ldap server to authenticate the user. 

Relevant docs:
- https://ldap3.readthedocs.io/en/latest/connection.html#
- https://www.programcreek.com/python/example/119020/ldap3.ServerPool

Tasks:
- Mention the possibility of multiple LDAP servers in the deployment documentation

Out of scope:
- Application tests with multiple LDAP servers

Acceptance criteria:
- Backwards compatible settings in the docker compose (comma-separated list)

Assumptions:
- Only the URL differs between LDAP servers, but lookup user and credentials are the same.
- No additional code paths are needed in the external server, so feature tests won't need to be run with both one and two LDAP-servers.

**Comment by fniessink** [comment]
Relevant docs:
- https://ldap3.readthedocs.io/en/latest/connection.html#
- https://www.programcreek.com/python/example/119020/ldap3.ServerPool
-
