### ISSUE TITLE
Conflicting dependencies in requirements.txt files

### ISSUE THREAD

**Issue by wkoot** [ICTU/quality-time#4159]
**Describe the bug**
It is not possible to install the various requirement.txt files for components in a single execution

**To Reproduce**
1. Open one of the component dirs in terminal 
2. Execute `pip install -r requirements\requirements-base.txt -r requirements\requirements.txt  -r requirements\requirements-dev.txt -r ..\shared_python\requirements\requirements-base.txt -r ..\shared_python\requirements\requirements-dev.txt`
3. See error

**Expected behavior**
Running pip install on all requirements.txt files of a component at once should not fail because of conflicting dependencies

**Your environment (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser -
 - Quality-time version: v4.1.0

**Additional context**
Overview of encountered mismatches (there are more but these give particular errors)
* astroid==2.11.5 and astroid==2.11.6
* black==22.3.0 and black==22.6.0
* cachecontrol[filecache]==0.12.10 and cachecontrol[filecache]==0.12.11
* certifi==2021.10.8 and certifi==2022.5.18.1
* click==8.0.4 and click==8.1.3
* click==8.1.2 and click==8.1.3
* cyclonedx-python-lib==1.3.0 and cyclonedx-python-lib==2.4.0
* cyclonedx-python-lib==2.3.0 and cyclonedx-python-lib==2.5.1
* cyclonedx-python-lib==2.4.0 and cyclonedx-python-lib==2.5.1
* dill==0.3.4 and dill==0.3.5.1
* lxml==4.9.0 and lxml==4.9.1
* pbr==5.8.1 and pbr==5.9.0
* pip-audit==2.3.1 and pip-audit==2.4.0
* pip-tools==6.6.2 and pip-tools==6.8.0
* platformdirs==2.5.1 and platformdirs==2.5.2
* pygments==2.11.2 and pygments==2.12.0
* pylint==2.14.1 and pylint==2.14.4
* pyparsing==3.0.7 and pyparsing==3.0.9
* pyparsing==3.0.8 and pyparsing==3.0.9
* requests==2.27.1 and requests==2.28.1
* safety==1.10.3 and safety==2.0.0
* types-setuptools==57.4.14 and types-setuptools==57.4.17
* types-setuptools==57.4.17 and types-setuptools==57.4.9
* types-toml==0.10.4 and types-toml==0.10.7
* types-toml==0.10.5 and types-toml==0.10.7
* typing-extensions==4.1.1 and typing-extensions==4.2.0
* urllib3==1.26.8 and urllib3==1.26.9
* vulture==2.4 and vulture==2.5
* wrapt==1.13.3 and wrapt==1.14.1
* wrapt==1.14.0 and wrapt==1.14.1

**Comment by fniessink** [comment]
It seems dependabot is not updating the Python components. There have been no PRs for the Python components recently (except the shared python code). Not sure why. We do start all dependabot updates at the same time. Maybe there's some limit there that we hit? I'll separate the times, e.g. 04:00, 04:01, 04:02, ...

**Comment by fniessink** [comment]
Dependabot config changed: #4162. Now waiting till tomorrow to see whether this fixes anything.

**Comment by fniessink** [comment]
We have had Dependabot PR's for Python components, so it seems it (still/again) works.
