### ISSUE TITLE
Replace date picker with a date picker widget that supports React 18

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-time#4467]
Possible candidates:
- https://www.npmjs.com/package/react-semantic-ui-datepickers

Note: preferably a data picker that supports Semantic UI React.

Tasks:
- Update frontend code.
- Remove suppression of semantic-ui-calendar-react-17 in the deadpendency config.

**Comment by Sebastiaan127001** [comment]
@fniessink 
is this useful?
https://www.npmjs.com/package/react-semantic-ui-datepickers
https://github.com/arthurdenner/react-semantic-ui-datepickers/releases/tag/v2.17.1
