### ISSUE TITLE
Creating an issue in Jira does not work

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-time#4586]
**Describe the bug**
Creating an issue with the "Create issue" button results in a 400 Client error.

**To Reproduce**
Steps to reproduce the behaviour:
1. Configure an issue tracker.
2. Create an issue.
3. See error in toaster: "Error creating issue: 400 Client Error for url: https://jira/rest/api/2/issue"
4. See error in log: `Creating a new issue at https://jira/rest/api/2/issue failed: 400 Client Error:  for url: https://jira/rest/api/2/issue`

**Your environment (please complete the following information):**
 - Quality-time v4.4.0

**Additional context**
Reported by @Sebastiaan127001 

**Upstream issues**
It seems labels cannot be added via the Jira API unless they are on the create and/or edit screen:
- Bug: https://jira.atlassian.com/browse/JRASERVER-27929 
- Suggestion: https://jira.atlassian.com/browse/JRASERVER-27936.

**Comment by Sebastiaan127001** [comment]
![image](https://user-images.githubusercontent.com/95095453/191337273-f8a57ad7-3888-4a34-912f-20ed434ad8f1.png)

**Comment by fniessink** [comment]
Todo:
- Explain in Labels warning that Jira needs to be configured by a Jira-admin to add the labels field to the "create" screen
- Color fields red when value is invalid or none
