### ISSUE TITLE
Filter SARIF source on severities.

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#4615]
**Is your feature request related to a problem? Please describe.**
The Interpretation of the SARIF results file from a Trivy scan ignores the serverity status.
![image](https://user-images.githubusercontent.com/95095453/192484784-ef38369e-d3ec-465c-b349-4b4a416d8266.png)
The error level, however, is being used.

**Describe the solution you'd like**
A way for end users to easily filter out the critical CVE's.

Maybe this can be combined with this issue: https://github.com/ICTU/quality-time/issues/3328

**Comment by fniessink** [comment]
Closed in favor of #3328.
