### ISSUE TITLE
When running on Docker Swarm the renderer creates PDF of webpage external to Quality-time

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-time#4758]
We have the weird situation where a user generates a PDF export of a quality-report via the API and gets a PDF not with a quality report but with the login page of another tool running on the same Docker Swarm. The issue is easy to reproduce by invoking the PDF export API twice at the same time, but also happens when called once. 

This doesn't seem to be a Quality-time bug, but maybe we can prevent the issue by changing the renderer. It currently accesses the quality report to export via the proxy. Maybe if the renderer doesn't use the proxy we prevent this problem?

**Comment by wkoot** [comment]
Setting the proxy to be the www container in the swarm, without changing the renderer, is a solution.
Adding this to the documentation should suffice?

**Comment by fniessink** [comment]
Docs as currently written are correct. This was a local issue at ICTU.
