### ISSUE TITLE
Get the maxResults Jira parameter from Jira itself instead of hardcoding it

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-time#4789]
The maxResults parameter is used in the collector en the external server (IssueTracker class).

**Comment by wkoot** [comment]
The [Get application property](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-jira-settings/#api-rest-api-3-application-properties-get) requires admin permissions, which makes this api unfit. It seems that `rest/api/2/mypreferences?key=jira.search.views.default.max` works.
There also seem to be various properties that control the parameter, `jira.search.views.default.max`, `jira.search.views.max.limit`, and `jira.search.views.max.unlimited.group`. However, the unlimited.group setting no longer seems to be listed in https://confluence.atlassian.com/adminjiraserver0820/configuring-advanced-settings-1095777708.html
