### ISSUE TITLE
Add tip to docs about source version metric

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-time#5283]
Source version metric can be used to monitor major/minor/patch updates. 

@Sebastiaan127001, please elaborate.

**Comment by Sebastiaan127001** [comment]
This tip is useful when you are responsible for upgrading tools in the pipeline. If you decide with your development team that you are only interested in the major and minor updates of tools and want to ignore any patch updates. The following settings can be helpful.

Leave the metric direction default, i.e. a higher version number is better.
Set the metric target to the first to digits of the latest available software version. So if the latest is 3.9.4, set it to 3.9.
Set the metric near target to only the first digit, so in this example that will be 3.

The result will be that when there is a minor update, this metric will turn yellow. So, suppose the version of your tool is at version 2.12.15 and the latest version available is 2.13.2 this metric will turn yellow.
If there is only a patch update, the metric will stay green. If there is a major update, the metric will turn red. 
So when we have 2.9.3 and the version available is 3.9.1 the metric will turn red.

**Comment by Sebastiaan127001** [comment]
Similarly, we can add to the documentation the tip to change ignore filters  (black list) into include filters (white list). This is can be use for instance with the "job runs" metric. For this, one can use the positive lookahead functinonality of regular expressions, e.g. ^(?!job-to-include).*$

**Comment by fniessink** [comment]
Add the documentation text to `components/shared_data_model/src/shared_data_model/metrics.py` using the `documentation=` key. Consider using the {tip} admonition,  see https://learning-readthedocs.readthedocs.io/en/latest/Options/admonition.html
