### ISSUE TITLE
Make health check files group writeable for a configurable user to ease use in OpenShift

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-time#5310]
`RUN chgrp -R 0 /home/collector && chmod -R g=u /home/collector`

Related issues: #5311 and #5312.

**Comment by wkoot** [comment]
Sadly, the health_check file stubbornly remains `collector:nogroup`:
```
/home/collector # chgrp 0 health_check.txt
chgrp: changing group of 'health_check.txt': Operation not permitted

/home/collector # chown :0 health_check.txt
chown: changing group of 'health_check.txt': Operation not permitted
```

It is possible to add user root to `nogroup` with `addgroup root nogroup` and make the file group-writable (within the `HEALTHCHECK CMD` as it does not exist on start), but this still does not allow writing to the file:
```
/home/collector # ls -l health_check.txt && echo "" > health_check.txt ; ls -l health_check.txt
-rw-rw-r--    1 collecto nogroup         26 Feb 23 21:52 health_check.txt
/bin/sh: can't create health_check.txt: Permission denied
-rw-rw-r--    1 collecto nogroup         26 Feb 23 21:52 health_check.txt
/home/collector # groups `whoami`
root bin daemon sys adm disk wheel floppy dialout tape video nogroup
```
However, this is still possible as the collector user:
```
~ $ ls -l health_check.txt && echo "" > health_check.txt ; ls -l health_check.txt
-rw-rw-r--    1 collecto nogroup         26 Feb 23 21:53 health_check.txt
-rw-rw-r--    1 collecto nogroup          1 Feb 23 21:53 health_check.txt
```

**Comment by wkoot** [comment]
History
https://github.com/ICTU/quality-time/commit/8aca9ef14bb4947a3cac52a528189a8079fecd8e
https://github.com/ICTU/quality-time/commit/2decc7a5df872428c30a0be488ea0a81892f23ff
