### ISSUE TITLE
Job runs metric shows jobs outside time window

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#5313]
**To Reproduce**
Steps to reproduce the behaviour:
1. Set a metric 'Job runs within time period' to 7 days (in source config)
2. Click on results tab (metric entities)
3. see job runs from earlier that 7 days ago

**Comment by fniessink** [comment]
@Sebastiaan127001, please add information on the source type? Jenkins, GitLab, Azure DevOps? And a screenshot would also be nice.

**Comment by Sebastiaan127001** [comment]
@fniessink I was not able to reproduce it with Jenkins. I did manage, however, to reproduce it with GitLab. See the below screenshot. I set the look back date to 2 days and the entities tab show metrics from 3 days as well.

**Comment by Sebastiaan127001** [comment]
![image](https://user-images.githubusercontent.com/95095453/221544786-d4dde239-2306-41ae-8c82-e9e7c9a4ff0a.png)

**Comment by Sebastiaan127001** [comment]
![image](https://user-images.githubusercontent.com/95095453/221545084-9058315a-a92d-4b24-8309-5ccb57850e29.png)

**Comment by Sebastiaan127001** [comment]
If these screenshots do not suffice, let have a call, so I can demo this.
