### ISSUE TITLE
Show the user as logged out in the frontend as soon as the session expires

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-time#5327]
**Is your feature request related to a problem? Please describe.**
When the user session expires, the frontend does not automically show the user as logged out.

**Describe the solution you'd like**
As soon as the session expires, log out the user from the frontend.

In App.js, onComponentMount, set an event handler that fires when the session expires and invoked `set_user(null)`

CC: @Sebastiaan127001

**Comment by Sebastiaan127001** [comment]
relates to https://github.com/ICTU/quality-time/issues/3380
