### ISSUE TITLE
Failed CI-jobs does not support pipeline runs of GitLab

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#5330]
**Describe the bug**
It would be useful if Quality-time supports the number of successful and failed pipeline runs. In the metric 'Failed CI-jobs', it says it does, but it does not.

This could be incorporated in the metric 'Job runs within time period' making the 'Failed CI-jobs' obsolete.

**Screenshots**
![image](https://user-images.githubusercontent.com/95095453/216105025-784e2d4e-a7dd-47e1-a0a2-10ce247bc126.png)

**Comment by fniessink** [comment]
We're going to try and fix this completely. See #5662.
