### ISSUE TITLE
Add metric Pipeline Run Duration

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#5348]
**Is your feature request related to a problem? Please describe.**
The team (G) is trying to optimise their pipeline. They want the pipeline to run within the hour so that the testers have quick feedback.

As a quality manager, I would like to see the duration of the last run of the pipeline. I am also interested in the average duration of the pipeline runs in the past X days.

**Describe the solution you'd like**
There already is a metric for performance test duration and manual test duration. I would like to have a metric for 'Pipeline Run Duration'. I would like to be able to use GitLab or Jenkins as a source.
Furthermore, I believe the default tag 'testability' is a good candidate.

**Comment by fniessink** [comment]
Duplicated by #6423.
