### ISSUE TITLE
Spike: alpine as base image for as many containers as possible

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-time#5400]

**Comment by wkoot** [comment]
both frontend and renderer already use `node:18.14.0-alpine3.17`
mongo-express already builds from alpine

mongo does not have an alpine version
- https://github.com/docker-library/mongo/blob/master/5.0/Dockerfile

Only used in dev/ci, placing out of scope:
selenium/standalone-firefox does not offer an alpine version
osixia/openldap and osixia/phpldapadmin do not offer alpine versions
- https://github.com/osixia/docker-phpLDAPadmin/blob/stable/image/Dockerfile
- https://github.com/osixia/docker-openldap/blob/master/image/Dockerfile
- https://github.com/osixia/docker-web-baseimage/blob/stable/image/Dockerfile
- https://github.com/osixia/docker-light-baseimage/blob/master/image/Dockerfile
