### ISSUE TITLE
Show the number of days when using calendar date.

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#5447]
**Is your feature request related to a problem? Please describe.**
A token will expire in 180 days, so I want to create a Time Remaining metric to measure the days left. When adding the Calendar Date source, I get the option to enter a date. Now I need to calculate, somehow, what date it is in 180 days from today.

**Describe the solution you'd like**
It would be useful if Quality-time has the option to enter the number of days from now, OR at least shows the number of days from now the selected date is.

**Describe alternatives you've considered**
This issue is related to https://github.com/ICTU/quality-time/issues/5123, but it works on a different field. This issue is for Calendar date and the related one is for Technical Debt End date.

**Comment by fniessink** [comment]
This issue has already been realised by #5123.
