### ISSUE TITLE
Bar charts are unreadable with a minimum (<3) number of metrics in that subject or with that label

### ISSUE THREAD

**Issue by denniebouman** [ICTU/quality-time#5792]
**Describe the bug**
When selecting (or comparing) 2 or more dates, the bar charts are unreadable when there are a minimum (<3) number of metrics in that subject or with that label.

**To Reproduce**
Steps to reproduce the behaviour:
1. Select 2 or more number of dates (Settings - Number of dates)
2. Optional select "Time between dates"
3. See bar charts 

**Expected behaviour**
Shows all bar charts with a fixed width or a minimum (readable) width. 
Suggestion: use the width as currently used for 20 metrics.

**Screenshots**
<img width="530" alt="image" src="https://user-images.githubusercontent.com/10399140/229075937-c4a2b91d-466d-4f38-b418-f48b724f3e83.png">

**Comment by Sebastiaan127001** [comment]
@fniessink, I have been discussing this yesterday with @ptrr . Let's discuss this in the refinement. Based on research, there are better ways to display this data. Peter has a book on this. We could use this for instance.: https://media.geeksforgeeks.org/wp-content/uploads/20210526083650/FinalPhotoMethod2.jpg
