### ISSUE TITLE
Add check for best practice configuration

### ISSUE THREAD

**Issue by eric-nieuwland** [ICTU/quality-time#581]
In Git a best practice is to deny direct commits onto the master branch and update it through merge requests only.
It would be nice to be able to verify whether such best practice is applied to a repository or - more generally - any other service.

**Comment by fniessink** [comment]
Nice idea, but somewhat outside the scope of Quality-time. If there was such a "best practice checker/linter", it could be a source for Quality-time, but I don't think Quality-time itself should do this work.
