### ISSUE TITLE
Cxsast collector http 500 error

### ISSUE THREAD

**Issue by ds-o** [ICTU/quality-time#593]
The CXSAST collector stores previously requested report-ids in a cache:

https://github.com/ICTU/quality-time/blob/3bcde436b34c52d9a4c9117c046a1e23db45eb46/components/collector/src/source_collectors/cxsast.py#L89

If more than 256 items are in the cache, the last one gets pushed out:

https://github.com/ICTU/quality-time/blob/3bcde436b34c52d9a4c9117c046a1e23db45eb46/components/collector/src/source_collectors/cxsast.py#L75

Issue: The servers clears the reports directory every night because it grows very large. This can create a situation where the reportfile no longer exists on disk, however the report-id is still in the cache and the collector will try to fetch it from the API. Which causes an error:

```
Traceback (most recent call last):
  File "/collector/source_collectors/source_collector.py", line 76, in safely_get_source_responses
    responses = self.get_source_responses(api_url)
  File "/collector/source_collectors/cxsast.py", line 99, in get_source_responses
    responses.append(self.api_get(f"reports/sastScan/{report_id}", token))
  File "/collector/source_collectors/cxsast.py", line 53, in api_get
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://xxxxx/cxrestapi/reports/sastScan/1819536
```

Proposed solution: clear the reportid from the cache if the following line results in HTTP 500, because this means the report XML has been deleted from the disk:

https://github.com/ICTU/quality-time/blob/3bcde436b34c52d9a4c9117c046a1e23db45eb46/components/collector/src/source_collectors/cxsast.py#L99

**Comment by fniessink** [comment]
Duplicate (but with useful info) of #468.

**Comment by milenk** [comment]
Better solution would be that every report is deleted from the QT itself immediately after it is read. That would mean that the folder would not grow and will be no need for cleaning. I'm working on it (#468).

**Comment by fniessink** [comment]
@milenk Does that mean that in your solution Checkmarx will have to create a new report every 15 minutes?

**Comment by ds-o** [comment]
@milenk the reports (XML files) are deleted on the Checkmarx server from the folder c:\CxReports every night by a scheduled job. 

This causes the Checkmarx API call which retreives the report (reports/sastScan/{report_id}) to fail, because there is an entry for the generated report in the Checkmarx database, but the physical XML file to which it refers no longer exists.
