### ISSUE TITLE
Checkbox for trusted sources with self-signed certificates

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#6152]
**Is your feature request related to a problem? Please describe.**
When configuring a source that has a self-signed certificate, the user gets an error because Quality-time cannot validate the certificate. This is a problem when the user trusts the source and wants to connect to it.

![image](https://github.com/ICTU/quality-time/assets/95095453/b05e2e0c-47fb-4ca4-8164-db9a662c7c31)

**Describe the solution you'd like**
I would be useful if the entry field of the source URL has a checkbox to trust the source.
![image](https://github.com/ICTU/quality-time/assets/95095453/1683b87e-08f7-4765-a618-989008ecc515)

In the code this would be as follows, if we use request library.
import requests;
self.session = Session()
self.session.verify = False

**to do**
add to the error message:
if you trust this source, tick the checkbox

**Comment by fniessink** [comment]
This issue should be solved by installing a valid certificate on the source.
