### ISSUE TITLE
Harbor source forces collector to restart

### ISSUE THREAD

**Issue by denniebouman** [ICTU/quality-time#6220]
**Describe the bug**
Harbor source forces collector to restart. 
Filtering Projects or Repositories with Harbor as source occurs when all the results (artifacts) from Harbor are collected. When there are many results from/in Harbor, this takes longer than the set timeout of the health check, which forces a restart of the collector container.
To fix this bug, filter before the results are collected.

**To Reproduce**
Steps to reproduce the behaviour:
1. Configure Security Warnings Metric
2. Add Harbor as source and configure (there should be many artifacts in Harbor)
3. Collector will be restarted after healthcheck timeout (10 minutes?)
4. Measurement is absent (no recent measurement)

**Expected behaviour**
Vulnerabilities will be shown in QT (if present) and collector will not be restarted

**Your environment (please complete the following information):**
 - Quality-time version: v4.10.0

**Comment by fniessink** [comment]
Cause is that the filtering by project/repo is applied after collecting all the data. Which can take a long time on a Harbor with many projects/repo's. 

Fix by:
- Applying the filter as early as possible
- Limiting the number of projects and/or repo's? I.e. throw an error if the number of projects and/or repositories exceeds a certain limit.
