### ISSUE TITLE
Filter metrics having linked issues

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#6256]
**Is your feature request related to a problem? Please describe.**
It would be useful to see a team's progress on metrics, having a linked Jira issue.
Currently, when a team member tells me he/she has merged a branch that should fix all issues, I have to scroll to located all the metrics having linked issues.
Moreover, when I want to remove solved Jira issues from metrics to clean the report, I have to scroll to the report. This could be a lot faster when I only see metrics having linked issues.

**Describe the solution you'd like**
It would be useful to filter only metrics having linked issues. 

**Describe alternatives you've considered**
Full text search in browser.

**Additional context**
See also 
https://github.com/ICTU/quality-time/discussions/6255
https://github.com/ICTU/quality-time/issues/3127
https://github.com/ICTU/quality-time/issues/3331

**Comment by fniessink** [comment]
Realized by #8222 (clicking the Issues card hides metrics without linked issue).
