### ISSUE TITLE
Prevent overlapping metrics

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#6367]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when SonarQube reports a code smell and two metrics turn in near target state (yellow/amber). The team interprets this as a double penalty for only one mistake. The problem arises when the user configures the metric 'Violations' with SonarQube as a source and code_smell included in the filter and on the same Quality-time report exists a metric 'Complex units' for instance. When there is a complex unit in the source code, SonarQube reports this once, and it is reflected twice on the Quality-time report.
The user does not know if it is safe to remove the code_smell filter in the Violations metric because this could result in missing warnings from SonarQube. 

The following metrics seem to be included in the Violations - code_smell filter, but it is unclear if this is the complete list.
- Commented out code
- Complex units
- Duplicate lines ??
- Long units
- Many parameters

**Describe the solution you'd like**
That Quality-time warns the user which metrics have overlap to avoid duplicate warnings for the same violation.

**Comment by fniessink** [comment]
This issue will be realized by #8972.
