### ISSUE TITLE
Docker compose up does not work on mac m2.

### ISSUE THREAD

**Issue by Rodyb** [ICTU/quality-time#6842]
**Describe the bug**
Together with some of my colleagues we wanted to try Quality time. 

Unfortunately the building of the docker compose results in failures on a mac m2.
We have followed the instructions as per your documentation: https://quality-time.readthedocs.io/en/latest/intro.html#trying-it-out. 

All other docker compose and builds work fine on mac, except this. I have tried with multiple different macs, all the same problem. 
 
**To Reproduce**
Steps to reproduce the behaviour:
1. Clone the repository
2. `docker compose build`

**Expected behaviour**
- Build should succeed and spin up the containers

**Screenshots**
<img width="1029" alt="Screenshot 2023-08-17 at 14 10 15" src="https://github.com/ICTU/quality-time/assets/11462303/fc757a73-08c9-4aec-a8f1-b61d9af8b07d">

**Your environment (please complete the following information):**
 - Mac OSX Ventura
 - Quality-time version 5.0.0

**Additional context**
- Tried to run the build `DOCKER_DEFAULT_PLATFORM=linux/amd64 docker-compose build` however no luck
- Tried to add platform to the docker compose file `platform: linux/amd64` no luck either. 

Let me know if more input is needed. 

Kind regards,
Rody

**Comment by fniessink** [comment]
Hi, this is surprising as this works fine on my Mac M1. Do you have access to a Mac M1? If so, does it work there for you?

**Comment by fniessink** [comment]
Oh wait, I see what the problem is; should've looked at your screenshot more carefully right away. We use Alpine as base image and Alpine has this issue: https://gitlab.alpinelinux.org/alpine/abuild/-/issues/9996. It's annoying, but it's a trade-off between unstable builds of the master branch and larger Docker images. If you pull the most recent commit it should work.

**Comment by fniessink** [comment]
Closing this for now. Please let me know if you need more help.
