### ISSUE TITLE
PDF export has rendering issues

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#7208]
**Describe the bug**
When a report is being exported as PDF. The result has an unwanted layout.

![image](https://github.com/ICTU/quality-time/assets/95095453/60820e09-7ec2-49b4-bc0a-d77f49bf2017)

Please remove the animation feature before exporting it to PDF.

**Comment by fniessink** [comment]
Relevant RGL tickets:
- https://github.com/react-grid-layout/react-grid-layout/issues/103
- https://github.com/react-grid-layout/react-grid-layout/issues/1627
