### ISSUE TITLE
See percentage in metric 'Size (LOC)'

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#7247]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I need to report the composition of code and I can only see the number of code lines.

**Describe the solution you'd like**
In the entities tab, I would like the numbers per language also show the percentage of the total.
Additionally, I would like Quality-time to use a period or a space as a thousands separator to make it more readable. 
Read [this](https://en.wikipedia.org/wiki/Decimal_separator#:~:text=Space%2C%20the%20internationally%20recommended,in%20most%20English%2Dspeaking%20countries.) before implementing.

So, this will result in the following. 
total lines of code = 2.200 lines
CSS = 220 lines (10%)
Java = 1.540 lines (70%)
JavaScript = 440 lines (20%)

**Additional context**
![image](https://github.com/ICTU/quality-time/assets/95095453/ffd7d77f-bcde-42ad-a18f-12f660f349c1)

**Comment by fniessink** [comment]
@Sebastiaan127001, Please open a new issue for the thousands separator.
