### ISSUE TITLE
Prevent having overlapping metrics

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#7408]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when Quality-time reports have overlapping metrics. I am aware that part of this issue is related to the way the end users uses Quality-time. However, teams report to me, it can be confusing when, for instance, the there is a metric 'violations' with SonarQube as a source and 'long units' with the same source. There will be an inevitable overlap when there are long units reported. 

**Describe the solution you'd like**
To avoid the overlap, multiple solutions are possible.
1. We get rid of the metrics that are also included in other metrics. These are 'long units', 'many parameters', 'commented out code' and maybe more. The downside of this is that the new version will not be compliant with older versions, and you'll lose data when updating. Nevertheless, I do not see added value in reporting 'many parameters' separately.
2. We can leave the sub-metrics like 'many parameters' as is, but we change the 'violations' metric and improve the filter one can set in the source configuration. Currently, one can only change the type, that is: bug, code smell or vulnerability. But for code smell, we have several types of code smells. If we can filter out 'many parameters' in the violations metric, we can use it as a separate metric.

**Describe alternatives you've considered**
Don't use the sub-metrics like 'many parameters' when you have violations metric in place. Sounds right, but this is not very intuitive since new users will add all the metrics when setting up a board, not knowing there is overlap. Furthermore, the missing metrics metric will also report that you are missing these sub-metric, ignoring the fact that there is an overlap.

PS: there can also be overlap when using different sources that more or less do the same. Like having OWASP dependency-check and Trivy in place, you can have overlap. That is out of scope for now.

**Comment by fniessink** [comment]
This issue will be realized by #8972.
