### ISSUE TITLE
Limit toaster message overflow

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#7625]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when there is a connection issue and Quality-time keeps reporting this. The GUI shows a pile of unnecessary stacked toaster messages.

**Describe the solution you'd like**
I would like Quality-time to reuse a toaster message or make a toaster message persistent for as long as the rationale is valid. 

**Describe alternatives you've considered**
accept

**Additional context**
![Screenshot 2023-12-05 at 15 29 12](https://github.com/ICTU/quality-time/assets/95095453/c6d5cff7-a9d1-4a8a-880b-804a83776550)

**Comment by fniessink** [comment]
Prevent duplicate messages: https://fkhadra.github.io/react-toastify/prevent-duplicate
