### ISSUE TITLE
Configurable user session duration

### ISSUE THREAD

**Issue by wigledejong** [ICTU/quality-time#8177]
The time frame of login is short. We use quality time everyday in our stand-up session. But often I'm logged out when I want to change something. 

It would be useful to have a longer period, say 5 days that your login is valid or a clear messages on opening Quality-time that your login is expired.

**Comment by wkoot** [comment]
Add env var `SESSION_DURATION` to api server, defaulting to 5 days + docs. Check that this is also included by the cookie.
Frontend should not have an own implementation that checks for the duration of the session, only a handler for expired sessions
