### ISSUE TITLE
Limit the length of comments when metrics are collapsed.

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#8281]
When a metrics are collapsed, and technical debt comments have long texts, the metrics become unusably wide (row height). This forces the user to scroll a lot.

A metric comment should display no more than 1000 characters when the metric is collapsed (please test this thoroughly, when resizing your viewport to a narrower width the limit should be max 200 chars maybe?).

![image](https://github.com/ICTU/quality-time/assets/95095453/c3762963-6009-4dc9-9a3e-dd43f9f94749)

**Comment by fniessink** [comment]
This has been implemented for `SourceEntityAttribute`. Reuse this functionality for:
- [x] Measurement entity status rationale
- [x] Metric comments
