### ISSUE TITLE
Modify Proxy-pod to run Nginx as non Root user 

### ISSUE THREAD

**Issue by jeroenma** [ICTU/quality-time#8356]
The current configuration for the Proxy-pod in quality-time runs as root user. In some Kubernetes environments it is not allowed to run it as a root user. 

Request is to make it configurable to run it under a non-root user. The TCP-port probably has to change to a port number above 1024. 

So for backwards compatibility it has to be configurable of default it to 80.

**Comment by jeroenma** [comment]
I fixed the issues local by using standard Nginx image and move LISTEN to Quality Time config. 
No changes required to this image.

**Comment by wkoot** [comment]
@jeroenma would the changes as being drafted in https://github.com/ICTU/quality-time/pull/8526/files also work for your use case?
