### ISSUE TITLE
"Missing metrics" and "Metrics" metrics broken 

### ISSUE THREAD

**Issue by denniebouman** [ICTU/quality-time#8357]
# Missing metrics

**Describe the bug**
Missing Metrics Metric broken 

**To Reproduce**
Steps to reproduce the behaviour:
1. Configure Missing Metrics Metric
2. See Error

**Stacktrace**
Parse error
Traceback (most recent call last):
  File "/home/collector/base_collectors/source_collector.py", line 152, in __safely_parse_source_responses
    return await self._parse_source_responses(responses)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/collector/source_collectors/quality_time/missing_metrics.py", line 27, in _parse_source_responses
    reports = await self._get_reports(reports_response)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/collector/source_collectors/quality_time/base.py", line 25, in _get_reports
    reports = list(response_json["reports"])
                   ~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'reports'

**Your environment (please complete the following information):**
 - Browser: Chrome
 - Quality-time version: 5.9.0

# Metrics

**Describe the bug**
 Metrics Metric broken 

**To Reproduce**
Steps to reproduce the behaviour:
1. Configure Metrics Metric
2. See Error

**Stacktrace**
Connection error
[Errno 54] Connection reset by peer

**Your environment (please complete the following information):**
 - Browser: Chrome
 - Quality-time version: 5.9.0

**Comment by fniessink** [comment]
I can reproduce this locally. This is probably caused by changes in the API in v5.9.0, see #5791.
