### ISSUE TITLE
Open links (e.g. info-button) standard in new tab

### ISSUE THREAD

**Issue by sebastiaan-vonk** [ICTU/quality-time#842]
There are some clickable links (for example the small questionmark help-buttons in the metric tab, or links to sources like sonarqube in the Sources-tab). When I click a link it opens in the same tab, so I have to click back to go back to the report. It would be nice if these would standard open in a new tab, so I always keep my report open.

Of course I can right-click to open the link, but I'm lazy :)

**Comment by fniessink** [comment]
WCAG recommends to be conservative with links opening in new windows (see https://www.w3.org/TR/WCAG20-TECHS/G200.html) but help links are an exception, so I'll change those.
