### ISSUE TITLE
Slow interface

### ISSUE THREAD

**Issue by denniebouman** [ICTU/quality-time#8436]
**Describe the bug**
For our project (that contains quite a lot of metrics) the loading speeds of various pages are quite long. The main overview page almost always takes more than 7 seconds to load, which seems quite slow. It makes navigating through the pages quite frustrating.

**Expected behaviour**
Loading times are more acceptable (at most a few seconds).

**Your environment (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Quality-time version: Quality-time v5.5.0

**Comment by fniessink** [comment]
Fixed by giving the Mongo container more memory (3GB instead of 1,5GB).
