### ISSUE TITLE
Add GitlabCI as source for metric 'Unused CI jobs'

### ISSUE THREAD

**Issue by sebastiaan-vonk** [ICTU/quality-time#851]
My project runs from GitlabCI. For the metric 'Failed CI-jobs' I am able to select this as source, for the metric 'Unused CI jobs' I am not able to select GitlabCI as source.

Related issue: 643.

**Comment by sebastiaan-vonk** [comment]
Just noticed we still use an older version (v.0.18.0). Please close if no longer relevant.

**Comment by fniessink** [comment]
I think we didn't implement this because we assumed (incorrectly?) Gitlab pipelines only run on code changes and not periodically. However, I now notice this: https://docs.gitlab.com/ee/user/project/pipelines/schedules.html so we'll add Gitlab as source for the unused CI-jobs metric.
