### ISSUE TITLE
Setting 'Metric scale' to percentage does not always cause related fields to update

### ISSUE THREAD

**Issue by sebastiaan-vonk** [ICTU/quality-time#852]
I create a new metric. For example 'Test line coverage'. I want the metric to count on 'percentage' instead of the default 'count'. I set the field 'Metric scale' to percentage. The related fields 'Metric target' and 'Metric near target' do not always automatically update. I have to switch to the Sources tab and back to Metric. If I now change the value to percentage, it will update the related fields.

**Comment by sebastiaan-vonk** [comment]
Just noticed we still use an older version (v.0.18.0). Please close if no longer relevant.

**Comment by fniessink** [comment]
Works for me with v1.1.0. Please reopen if you still have the issue after updating to v1.1.0 or newer. Thanks!
