### ISSUE TITLE
Filter metrics requiring actions via the dashboard 

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#8938]
Tasks:
- Add a "Metrics requiring action" card to the dashboard, showing the number of red, yellow, and white metrics in a little table.
- When clicking the card, only show the metrics requiring action via the existing setting.
- Make the card hideable via the settings.

**Comment by fniessink** [comment]
Makes sense, but maybe not for the legend card, but rather a card that has the number of metrics in different states. Maybe the Legend card could do both at the same time, but I'm not sure yet.
