### ISSUE TITLE
Jira issue type names are in Jira default language instead of English

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#9101]
**Describe the bug**
I believe this issue occurs when the user has JIRA in another language. In that case, Quality-time shows the issue types in that language. Users report that this is unwanted behaviour. 

**Expected behaviour**
Can we use the Jira issue type names in English?

**Screenshots**
![image](https://github.com/ICTU/quality-time/assets/95095453/9610ded9-7f17-418f-82e4-5036dab272fb)

**Comment by fniessink** [comment]
Investigate whether we can force Jira to always returns labels in English. If not, the user whose token is used should  configured the desired language (i.e. English) in Jira itself.

**Comment by fniessink** [comment]
I haven't been able to find a way to force Jira to always returns labels in English.
