### ISSUE TITLE
403 error with Dependency Track

### ISSUE THREAD

**Issue by MaxStaallekker** [ICTU/quality-time#9168]
**Describe the bug**
When adding Dependency Track as a source without adding any projects information, I get a 403 'Forbidden' error.
Even though the API key and URL are correct.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Add Metric: Security Warnings' and add 'Dependency Track' as source.
2. Add the relevant information to connect to the Dependency Track instance and leave the project information empty.

**Expected behaviour**
The expected behaviour is to see all the vulnerable dependencies from every project in Dependency Track.

**Your environment (please complete the following information):**
  - Quality-time version: 5.13.0

**Comment by denniebouman** [comment]
It looks like this is a rights issue on the dependency track side. The ICTU support team has fixed this (manually for now)

**Comment by fniessink** [comment]
Correct. See IES-8669.
