### ISSUE TITLE
Checkmarx metric URL should point to report

### ISSUE THREAD

**Issue by ds-o** [ICTU/quality-time#919]
The Checkmarx CxSast URL in the Source column points to:

https://xxxx/CxWebClient/projectscans.aspx?id=123

This is an overview of all scans for the project. It should point directly to the last scan results:

https://xxxx/CxWebClient/ViewerMain.aspx?scanId=123456&ProjectID=123

Also, the URL should open in a new tab.

![image](https://user-images.githubusercontent.com/21058511/71894196-e3a97d80-314d-11ea-8a9a-05300a454885.png)

**Comment by fniessink** [comment]
Opening links in a new tab is not recommended, see https://www.w3.org/TR/WCAG20-TECHS/G200.html.

**Comment by ds-o** [comment]
Maybe example 2 from the w3 link is applicable here?

**Comment by fniessink** [comment]
Opening the link inplace doesn't "break or destroy the secure session" so I don't think so.
