### ISSUE TITLE
False positive functionality not working

### ISSUE THREAD

**Issue by ds-o** [ICTU/quality-time#922]
When marking an issue as a false positive, the API call results in a 404 and the changes are not saved:

![image](https://user-images.githubusercontent.com/21058511/71904408-5161a380-3166-11ea-961b-f96fbbe1d726.png)

In the browser console, the following API call QT makes results in 404:

http://www.quality-time.xxxx/api/v1/measurement/xxxxxxxxxxx/source/xxxxxxxxxxxxxxx/entity/10062:359:13:3:GET:https://xxxxxxxxx.org/aa/TestPage.jsf/rationale

**Comment by fniessink** [comment]
Looks like this may be specific to the issue key (it has slashes). Solution may be to URL-encode issue keys. @dicksnel, which source type is this?
