### ISSUE TITLE
Checkmarx tab is missing

### ISSUE THREAD

**Issue by ds-o** [ICTU/quality-time#923]
The following metric has Checkmarx CxSast configured as a source. The number of findings from Checkmarx are reported in the total number of findings, but there is no Checkmarx tab with the details:

![image](https://user-images.githubusercontent.com/21058511/71904639-c9c86480-3166-11ea-939f-873ea232f5f7.png)

![image](https://user-images.githubusercontent.com/21058511/71905957-7572b400-3169-11ea-9ebd-1e82232fa4c0.png)

**Comment by fniessink** [comment]
This is due to the cumbersome scan reports API of Checkmarx. Getting the details is possible, but too complicated.
