### ISSUE TITLE
Allow for using sources for more than metric

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-time#927]
This would make maintenance (changing urls or credentials) easier.

**Comment by enwelder** [comment]
To elaborate on this issue:
Depending on the size of the issue, maintaining URL's and credentials in the way it is done now is very labor intensive.
Every metric gets it's own definition of a source, with own URL and credentials.
If any of these change, a very high number of records need to be updated to refect the change in URL or credentials.
For example, the IWS project has about 20 modules with each about 20-25 metrics. If we need to replace any of the urls or credentials, we could easily be required to update 100+ records :(

What would be useful is to have a central place to configure urls and credentials which can be reused in the metrics.
