### ISSUE TITLE
Using Trivy as a source for Security warnings results in parse error

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#9711]
trivy version 0.55.2

We have followed the readthedocs and it still results in a parse error.

this is the command used to create the json 
trivy image --debug --offline-scan --input target/tar_images/${IMAGE_NAME}.tar -f json -o target/testresults/trivy/trivy-results.json

![image](https://github.com/user-attachments/assets/587d9790-84dd-4f0a-9a0c-9cb49369d3eb)
![image](https://github.com/user-attachments/assets/53124cfc-b5b2-4258-b982-7df1c62f8012)

**Comment by fniessink** [comment]
Please mail me the offending JSON file, thanks!

**Comment by fniessink** [comment]
This is apparently caused by a breaking change in Trivy v0.20.0: https://github.com/aquasecurity/trivy/discussions/1050
