### ISSUE TITLE
Allow for measuring Dependency-Track last analysis date 

### ISSUE THREAD

**Issue by denniebouman** [ICTU/quality-time#9764]
**Is your feature request related to a problem? Please describe.**
DependencyTrack can display when an SBoM was last uploaded and when it was last analyzed (regardless of the upload date).
The first date is currently used for the “source up-to-dateness” metric. 
Because DependencyTrack scans possible (new) vulnerabilities using a scheduler (separate from a more recent SBoM upload), this (execution) date is also important, but serves a different purpose, more as a “health check”.

**Describe the solution you'd like**
Add a new metric type, which can report on the “last executed/analysis date” and use the last analysis date specific for DependencyTrack.

Multiple sources may be able to be mapped to this new metric, for example: SonarQube last analysis date, PerformanceTest last execution date, OWASP last analysis date, etc.
Source-up-to-dateness could then remain a typical naming convention for example a file in Gitlab.

**Proposal for the new metric name:**
Last run date?
Last executed date?

**Describe alternatives you've considered**
Change the current metric to use the last analysis date, but both serve a different purpose.

**Comment by fniessink** [comment]
Tasks:
- Add a up-to-dateness type parameter to the Dependency-Track collector when used for source up-to-dateness with the values "last analysis", "last SBOM upload", "oldest of last analysis and last SBOM upload".
- Use the `metrics.lastOccurrence` field from the `/api/v1/project/project_uuid` endpoint response. This is the info that is used for the "Last Measurement" timestamp displayed in the UI. This field contains a unix timestamp, like the `lastBomImport` field.

Notes:
- Differentiating between "last analysis" and "last upload" is only relevant when the analysis can change without the source code (or other artefacts) changing. This is mainly the case with tools that track known vulnerabilities in dependencies. 

- DependencyTrack seems to use the `metrics.lastOccurrence` field from the `/api/v1/project/project_uuid` endpoint response for the "Last Measurement" timestamp displayed in the UI. This field contains a unix timestamp, like the `lastBomImport` field.

- The current `SourceUpToDateness` metric is supported by these sources.
  - [Anchore](https://quality-time.readthedocs.io/en/latest/reference.html#source-up-to-dateness-from-anchore)
  - [Anchore Jenkins plugin](https://quality-time.readthedocs.io/en/latest/reference.html#source-up-to-dateness-from-anchore-jenkins-plugin)
  - [Axe-core](https://quality-time.readthedocs.io/en/latest/reference.html#source-up-to-dateness-from-axe-core)
  - [Azure DevOps Server](https://quality-time.readthedocs.io/en/latest/reference.html#source-up-to-dateness-from-azure-devops-server)
  - [Bandit](https://quality-time.readthedocs.io/en/latest/reference.html#source-up-to-dateness-from-bandit)
  - [Calendar date](https://quality-time.readthedocs.io/en/latest/reference.html#source-up-to-dateness-from-calendar-date)
  - [Cobertura](https://quality-time.readthedocs.io/en/latest/reference.html#source-up-to-dateness-from-cobertura)
  - [Cobertura Jenkins plugin](https://quality-time.readthedocs.io/en/latest/reference.html#source-up-to-dateness-from-cobertura-jenkins-plugin)
  - [Checkmarx CxSAST](https://quality-time.readthedocs.io/en/latest/reference.html#source-up-to-dateness-from-checkmarx-cxsast)
  - [Dependency-Track](https://quality-time.readthedocs.io/en/latest/reference.html#source-up-to-dateness-from-dependency-track)
  - [Gatling](https://quality-time.readthedocs.io/en/latest/reference.html#source-up-to-dateness-from-gatling)
  - [GitLab](https://quality-time.readthedocs.io/en/latest/reference.html#source-up-to-dateness-from-gitlab)
  - [JaCoCo](https://quality-time.readthedocs.io/en/latest/reference.html#source-up-to-dateness-from-jacoco)
  - [JaCoCo Jenkins plugin](https://quality-time.readthedocs.io/en/latest/reference.html#source-up-to-dateness-from-jacoco-jenkins-plugin)
  - [Jenkins](https://quality-time.readthedocs.io/en/latest/reference.html#source-up-to-dateness-from-jenkins)
  - [Jenkins test report](https://quality-time.readthedocs.io/en/latest/reference.html#source-up-to-dateness-from-jenkins-test-report)
  - [JMeter CSV](https://quality-time.readthedocs.io/en/latest/reference.html#source-up-to-dateness-from-jmeter-csv)
  - [JUnit XML report](https://quality-time.readthedocs.io/en/latest/reference.html#source-up-to-dateness-from-junit-xml-report)
  - [NCover](https://quality-time.readthedocs.io/en/latest/reference.html#source-up-to-dateness-from-ncover)
  - [Robot Framework](https://quality-time.readthedocs.io/en/latest/reference.html#source-up-to-dateness-from-robot-framework)
  - [OpenVAS](https://quality-time.readthedocs.io/en/latest/reference.html#source-up-to-dateness-from-openvas)
  - [OWASP Dependency-Check](https://quality-time.readthedocs.io/en/latest/reference.html#source-up-to-dateness-from-owasp-dependency-check)
  - [OWASP ZAP](https://quality-time.readthedocs.io/en/latest/reference.html#source-up-to-dateness-from-owasp-zap)
  - [Performancetest-runner](https://quality-time.readthedocs.io/en/latest/reference.html#source-up-to-dateness-from-performancetest-runner)
  - [Quality-time](https://quality-time.readthedocs.io/en/latest/reference.html#source-up-to-dateness-from-quality-time)
  - [Robot Framework Jenkins plugin](https://quality-time.readthedocs.io/en/latest/reference.html#source-up-to-dateness-from-robot-framework-jenkins-plugin)
  - [SonarQube](https://quality-time.readthedocs.io/en/latest/reference.html#source-up-to-dateness-from-sonarqube)
  - [TestNG](https://quality-time.readthedocs.io/en/latest/reference.html#source-up-to-dateness-from-testng)
  - [Trello](https://quality-time.readthedocs.io/en/latest/reference.html#source-up-to-dateness-from-trello)

- ~From a migration point of view it seems best to introduce the new "analysis up-to-dateness" metric and then add support for it on a source by source basis.~
