### ISSUE TITLE
No alphabetic order in new metric menu

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#9857]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to add metric button
2. check select from all metric types
3. see the list in non-alphabetic order 

**Screenshots**
![image](https://github.com/user-attachments/assets/6b42c96d-d4d1-46c9-89ef-0d0a3050f88d)

**Comment by fniessink** [comment]
Might be related to #9855. Maybe because sorting is done by metric key instead of metric name?
