### ISSUE TITLE
Resolved JIRA issues are not done yet

### ISSUE THREAD

**Issue by ICTUEuropaLoket** [ICTU/quality-time#9931]
When JIRA issues are linked to a quality time metric as resolution for technical dept quality time uses the wrong status for marking it as completed.

The status resolved is also seen as the issue is done, but in most situation the JIRA ticket is in code review so not done yet and not merged into the dev/master branch. Only the status closed should be used to mark a JIRA issue, linked to solve technical dept, as completed.

**Comment by fniessink** [comment]
Jira issues have a status and a status category. See https://support.atlassian.com/jira-work-management/docs/workflows-and-statuses-for-the-board/. 

Jira statuses are configurable, there can be many, and their meaning is project specific (as illustrated above where "resolved" means "done except for code review and merging"). Jira status categories are not configurable and there are exactly three: todo, doing, and done. All Jira statuses map to one of the three Jira status categories. 

Quality-time uses the Jira status category of an issue, not its status, to determine whether an issue has been completed. It cannot use the Jira status, as Quality-time has no way of determining what they mean, except by looking at the Jira status category.

If Quality-time shows resolved issues as completed, then apparently the status "resolved" is mapped to the status category "done" in Jira, and that should be changed (in Jira) as "resolved" apparently doesn't mean "done" in this case.
